// Animal-derived items: muscle, organs, aquatic life, insects, eggs, dairy,
// and hominid tissue.
//
// All figures are per 100 g of the raw item unless the name says otherwise.
// `carb` is AVAILABLE carbohydrate — reference tables publish "carbohydrate by
// difference", which includes fibre, so fibre has been subtracted out here.
// That split matters: available carbohydrate is 17 kJ/g, fibre only 8.

export default [
  /* ---------------------------------------------------------------- meat -- */
  {
    id: 'beef_ground_80',
    name: 'Ground beef, 80/20',
    category: 'meat',
    tags: ['cattle', 'butchered'],
    source: 'USDA SR Legacy 23562',
    confidence: 'high',
    coverage: 'full',
    g: { water: 60.0, protein: 17.2, fat: 20.0, carb: 0, fiber: 0, ash: 0.8 },
    mg: { sodium: 66, potassium: 270, calcium: 16, magnesium: 17, phosphorus: 158, iron: 1.94, zinc: 4.18, copper: 0.06, manganese: 0.01, vitaminB2: 0.15, vitaminB3: 4.22, vitaminB5: 0.5, vitaminB6: 0.33, vitaminB1: 0.04, vitaminE: 0.17 },
    ug: { selenium: 15, vitaminB12: 2.14, vitaminB9: 7, vitaminK: 1.4, vitaminD: 0.1 },
  },
  {
    id: 'beef_sirloin',
    name: 'Beef sirloin, lean',
    category: 'meat',
    tags: ['cattle', 'butchered'],
    source: 'USDA SR Legacy 23232',
    confidence: 'high',
    coverage: 'partial',
    g: { water: 72.9, protein: 21.4, fat: 4.6, carb: 0, fiber: 0, ash: 1.1 },
    mg: { sodium: 54, potassium: 352, calcium: 17, magnesium: 24, phosphorus: 205, iron: 1.6, zinc: 3.8, copper: 0.08, vitaminB3: 5.9, vitaminB6: 0.6 },
    ug: { selenium: 24.9, vitaminB12: 1.3 },
  },
  {
    id: 'pork_loin',
    name: 'Pork loin',
    category: 'meat',
    tags: ['pig', 'butchered'],
    source: 'USDA SR Legacy 10023',
    confidence: 'high',
    coverage: 'partial',
    g: { water: 72.3, protein: 20.9, fat: 5.9, carb: 0, fiber: 0, ash: 1.1 },
    mg: { sodium: 51, potassium: 393, calcium: 16, magnesium: 25, phosphorus: 221, iron: 0.72, zinc: 1.8, copper: 0.06, vitaminB1: 0.87, vitaminB2: 0.25, vitaminB3: 5.1, vitaminB6: 0.56 },
    ug: { selenium: 32.8, vitaminB12: 0.63 },
  },
  {
    id: 'chicken_breast',
    name: 'Chicken breast, skinless',
    category: 'meat',
    tags: ['bird', 'butchered'],
    source: 'USDA SR Legacy 05062',
    confidence: 'high',
    coverage: 'full',
    g: { water: 73.9, protein: 23.1, fat: 1.2, carb: 0, fiber: 0, ash: 1.1 },
    mg: { sodium: 65, potassium: 334, calcium: 5, magnesium: 28, phosphorus: 213, iron: 0.37, zinc: 0.68, copper: 0.04, manganese: 0.015, vitaminB3: 10.6, vitaminB5: 0.96, vitaminB6: 0.6, vitaminB2: 0.09, vitaminE: 0.13 },
    ug: { selenium: 22.8, vitaminB12: 0.2, vitaminB9: 4, vitaminA: 6 },
  },
  {
    id: 'chicken_thigh',
    name: 'Chicken thigh, with skin',
    category: 'meat',
    tags: ['bird', 'butchered'],
    source: 'USDA SR Legacy 05096',
    confidence: 'high',
    coverage: 'partial',
    g: { water: 70.0, protein: 17.3, fat: 11.5, carb: 0, fiber: 0, ash: 0.8 },
    mg: { sodium: 78, potassium: 204, calcium: 8, magnesium: 18, phosphorus: 147, iron: 0.9, zinc: 1.5, vitaminB3: 4.5 },
    ug: { selenium: 15.4, vitaminB12: 0.5 },
  },
  {
    id: 'lamb_leg',
    name: 'Lamb leg',
    category: 'meat',
    tags: ['sheep', 'butchered'],
    source: 'USDA SR Legacy 17224',
    confidence: 'high',
    coverage: 'partial',
    g: { water: 70.0, protein: 20.3, fat: 8.8, carb: 0, fiber: 0, ash: 1.0 },
    mg: { sodium: 61, potassium: 320, calcium: 9, magnesium: 24, phosphorus: 182, iron: 1.8, zinc: 3.6, copper: 0.11, vitaminB3: 5.7 },
    ug: { selenium: 21.2, vitaminB12: 2.6 },
  },
  {
    id: 'venison',
    name: 'Venison',
    category: 'meat',
    tags: ['deer', 'wild', 'prey-part'],
    source: 'USDA SR Legacy 17163',
    confidence: 'high',
    coverage: 'partial',
    g: { water: 74.0, protein: 22.9, fat: 2.4, carb: 0, fiber: 0, ash: 1.2 },
    mg: { sodium: 51, potassium: 329, calcium: 7, magnesium: 23, phosphorus: 202, iron: 3.4, zinc: 2.1, copper: 0.21, vitaminB2: 0.5, vitaminB3: 5.7, vitaminB6: 0.37 },
    ug: { selenium: 9.7, vitaminB12: 1.9 },
  },
  {
    id: 'rabbit',
    name: 'Rabbit',
    category: 'meat',
    tags: ['wild', 'prey-part'],
    source: 'USDA SR Legacy 17180',
    confidence: 'high',
    coverage: 'partial',
    g: { water: 72.8, protein: 20.1, fat: 5.6, carb: 0, fiber: 0, ash: 1.2 },
    mg: { sodium: 41, potassium: 343, calcium: 12, magnesium: 25, phosphorus: 226, iron: 1.9, zinc: 1.4, vitaminB3: 7.2 },
    ug: { selenium: 15.9, vitaminB12: 7.1 },
  },
  {
    id: 'horse',
    name: 'Horse',
    category: 'meat',
    tags: ['butchered'],
    source: 'USDA SR Legacy 17153',
    confidence: 'medium',
    coverage: 'partial',
    g: { water: 73.6, protein: 21.4, fat: 4.6, carb: 0, fiber: 0, ash: 1.0 },
    mg: { sodium: 53, potassium: 360, calcium: 7, magnesium: 22, phosphorus: 195, iron: 3.8, zinc: 2.9 },
    ug: { selenium: 11, vitaminB12: 3.5 },
  },
  {
    id: 'duck_meat',
    name: 'Duck, skinless',
    category: 'meat',
    tags: ['bird', 'wild'],
    source: 'USDA SR Legacy 05140',
    confidence: 'medium',
    coverage: 'partial',
    g: { water: 73.8, protein: 18.3, fat: 5.9, carb: 0, fiber: 0, ash: 1.1 },
    mg: { sodium: 74, potassium: 271, calcium: 11, magnesium: 19, phosphorus: 203, iron: 2.4, zinc: 1.9, vitaminB3: 5.3 },
    ug: { selenium: 14, vitaminB12: 0.4 },
  },
  {
    id: 'turkey_breast',
    name: 'Turkey breast',
    category: 'meat',
    tags: ['bird'],
    source: 'USDA SR Legacy 05165',
    confidence: 'medium',
    coverage: 'partial',
    g: { water: 73.8, protein: 23.7, fat: 1.2, carb: 0, fiber: 0, ash: 1.1 },
    mg: { sodium: 63, potassium: 302, calcium: 12, magnesium: 28, phosphorus: 206, iron: 1.2, zinc: 1.7, vitaminB3: 6.4 },
    ug: { selenium: 24, vitaminB12: 0.4 },
  },
  {
    id: 'goat',
    name: 'Goat',
    category: 'meat',
    tags: ['butchered'],
    source: 'USDA SR Legacy 17168',
    confidence: 'medium',
    coverage: 'partial',
    g: { water: 75.8, protein: 20.6, fat: 2.3, carb: 0, fiber: 0, ash: 1.1 },
    mg: { sodium: 82, potassium: 385, calcium: 13, magnesium: 0, phosphorus: 180, iron: 2.8, zinc: 4.0 },
    ug: { selenium: 8.8, vitaminB12: 1.1 },
  },
  {
    id: 'bison',
    name: 'Bison',
    category: 'meat',
    tags: ['wild', 'prey-part'],
    source: 'USDA SR Legacy 17157',
    confidence: 'medium',
    coverage: 'partial',
    g: { water: 74.4, protein: 21.6, fat: 2.4, carb: 0, fiber: 0, ash: 1.1 },
    mg: { sodium: 56, potassium: 342, calcium: 9, magnesium: 23, phosphorus: 196, iron: 2.9, zinc: 3.4 },
    ug: { selenium: 11.3, vitaminB12: 2.9 },
  },

  /* --------------------------------------------------------------- organ -- */
  {
    id: 'beef_liver',
    name: 'Beef liver',
    category: 'organ',
    tags: ['cattle', 'prey-part', 'nutrient-dense'],
    source: 'USDA SR Legacy 13325',
    confidence: 'high',
    coverage: 'full',
    note: 'The densest micronutrient source in this biosphere. Vitamin A and copper are both an order of magnitude above anything else.',
    g: { water: 70.8, protein: 20.4, fat: 3.6, carb: 3.9, fiber: 0, ash: 1.3 },
    mg: { sodium: 69, potassium: 313, calcium: 5, magnesium: 18, phosphorus: 387, iron: 4.9, zinc: 4.0, copper: 9.76, manganese: 0.31, vitaminC: 1.3, vitaminE: 0.38, vitaminB1: 0.19, vitaminB2: 2.76, vitaminB3: 13.2, vitaminB5: 7.17, vitaminB6: 1.08 },
    ug: { selenium: 39.7, vitaminA: 4968, vitaminD: 1.2, vitaminK: 3.1, vitaminB7: 42, vitaminB9: 290, vitaminB12: 59.3, molybdenum: 100, chromium: 12 },
  },
  {
    id: 'chicken_liver',
    name: 'Chicken liver',
    category: 'organ',
    tags: ['bird', 'prey-part', 'nutrient-dense'],
    source: 'USDA SR Legacy 05027',
    confidence: 'high',
    coverage: 'full',
    g: { water: 76.5, protein: 16.9, fat: 4.8, carb: 0.7, fiber: 0, ash: 1.3 },
    mg: { sodium: 71, potassium: 230, calcium: 8, magnesium: 19, phosphorus: 297, iron: 8.99, zinc: 2.67, copper: 0.49, manganese: 0.26, vitaminC: 17.9, vitaminE: 0.7, vitaminB1: 0.3, vitaminB2: 1.78, vitaminB3: 9.73, vitaminB5: 6.23, vitaminB6: 0.85 },
    ug: { selenium: 54.6, vitaminA: 3296, vitaminD: 0.4, vitaminK: 0, vitaminB7: 187, vitaminB9: 588, vitaminB12: 16.6 },
  },
  {
    id: 'pork_liver',
    name: 'Pork liver',
    category: 'organ',
    tags: ['pig', 'prey-part', 'nutrient-dense'],
    source: 'USDA SR Legacy 10110',
    confidence: 'high',
    coverage: 'partial',
    g: { water: 71.1, protein: 21.4, fat: 3.6, carb: 2.5, fiber: 0, ash: 1.5 },
    mg: { sodium: 87, potassium: 273, calcium: 9, magnesium: 18, phosphorus: 288, iron: 23.3, zinc: 5.8, copper: 0.68, manganese: 0.34, vitaminC: 25.3, vitaminB2: 3.0, vitaminB3: 8.4 },
    ug: { selenium: 52.7, vitaminA: 6502, vitaminB9: 212, vitaminB12: 26 },
  },
  {
    id: 'beef_kidney',
    name: 'Beef kidney',
    category: 'organ',
    tags: ['cattle', 'prey-part'],
    source: 'USDA SR Legacy 13324',
    confidence: 'high',
    coverage: 'partial',
    g: { water: 77.9, protein: 17.4, fat: 3.1, carb: 0.3, fiber: 0, ash: 1.2 },
    mg: { sodium: 182, potassium: 262, calcium: 13, magnesium: 17, phosphorus: 257, iron: 4.6, zinc: 1.9, copper: 0.43, vitaminC: 9.4, vitaminB2: 2.84, vitaminB3: 8.0 },
    ug: { selenium: 141, vitaminA: 419, vitaminB9: 98, vitaminB12: 27.5 },
  },
  {
    id: 'beef_heart',
    name: 'Beef heart',
    category: 'organ',
    tags: ['cattle', 'prey-part'],
    source: 'USDA SR Legacy 13321',
    confidence: 'high',
    coverage: 'partial',
    g: { water: 77.1, protein: 17.7, fat: 3.9, carb: 0.1, fiber: 0, ash: 1.0 },
    mg: { sodium: 98, potassium: 287, calcium: 7, magnesium: 21, phosphorus: 212, iron: 4.3, zinc: 1.7, copper: 0.39, vitaminC: 2, vitaminB2: 0.9, vitaminB3: 7.5 },
    ug: { selenium: 21.8, vitaminB9: 3, vitaminB12: 8.5 },
  },
  {
    id: 'beef_brain',
    name: 'Beef brain',
    category: 'organ',
    tags: ['cattle', 'prey-part'],
    source: 'USDA SR Legacy 13319',
    confidence: 'medium',
    coverage: 'partial',
    g: { water: 77.0, protein: 10.9, fat: 10.3, carb: 1.1, fiber: 0, ash: 1.4 },
    mg: { sodium: 126, potassium: 274, calcium: 43, magnesium: 13, phosphorus: 362, iron: 2.0, zinc: 1.1, copper: 0.26, vitaminC: 10.7, vitaminB3: 3.6 },
    ug: { selenium: 21.3, vitaminB12: 9.5 },
  },
  {
    id: 'beef_tongue',
    name: 'Beef tongue',
    category: 'organ',
    tags: ['cattle', 'prey-part'],
    source: 'USDA SR Legacy 13330',
    confidence: 'medium',
    coverage: 'partial',
    g: { water: 68.0, protein: 14.9, fat: 16.1, carb: 0, fiber: 0, ash: 0.9 },
    mg: { sodium: 69, potassium: 315, calcium: 6, magnesium: 16, phosphorus: 161, iron: 2.9, zinc: 2.9, vitaminB3: 4.0 },
    ug: { selenium: 9.6, vitaminB12: 3.8 },
  },
  {
    id: 'beef_spleen',
    name: 'Beef spleen',
    category: 'organ',
    tags: ['cattle', 'prey-part', 'nutrient-dense'],
    source: 'USDA SR Legacy 13328',
    confidence: 'medium',
    coverage: 'partial',
    note: 'Unusually high in both iron and ascorbate for an animal tissue.',
    g: { water: 78.5, protein: 18.3, fat: 3.0, carb: 0, fiber: 0, ash: 1.4 },
    mg: { sodium: 85, potassium: 429, calcium: 10, magnesium: 22, phosphorus: 296, iron: 44.6, zinc: 2.1, copper: 0.27, vitaminC: 45.5, vitaminB2: 0.3 },
    ug: { selenium: 25, vitaminB12: 5.9 },
  },
  {
    id: 'beef_tripe',
    name: 'Beef tripe',
    category: 'organ',
    tags: ['cattle', 'prey-part'],
    source: 'USDA SR Legacy 13331',
    confidence: 'medium',
    coverage: 'partial',
    g: { water: 84.0, protein: 12.1, fat: 4.0, carb: 0, fiber: 0, ash: 0.5 },
    mg: { sodium: 97, potassium: 67, calcium: 69, magnesium: 13, phosphorus: 64, iron: 0.6, zinc: 1.4 },
    ug: { selenium: 12.5, vitaminB12: 1.3 },
  },
  {
    id: 'bone_marrow',
    name: 'Bone marrow',
    category: 'organ',
    tags: ['cattle', 'prey-part', 'fuel-dense'],
    source: 'USDA SR Legacy 13322',
    confidence: 'medium',
    coverage: 'macroOnly',
    note: 'Almost pure fat — the single densest fuel a carcass offers.',
    g: { water: 29.0, protein: 2.4, fat: 67.0, carb: 0, fiber: 0, ash: 0.5 },
    mg: { sodium: 44, potassium: 29, calcium: 20, phosphorus: 23, iron: 0.9 },
  },
  {
    id: 'blood_bovine',
    name: 'Blood, bovine',
    category: 'organ',
    tags: ['cattle', 'prey-part', 'fluid'],
    source: 'Composite of published haematology values',
    confidence: 'medium',
    coverage: 'partial',
    note: 'Iron concentration is driven almost entirely by haemoglobin.',
    g: { water: 80.9, protein: 17.3, fat: 0.2, carb: 0.1, fiber: 0, ash: 1.0 },
    mg: { sodium: 230, potassium: 110, calcium: 10, magnesium: 4, phosphorus: 40, chloride: 290, iron: 44, zinc: 0.7, copper: 0.1 },
    ug: { selenium: 12, vitaminB12: 0.6 },
  },

  /* ------------------------------------------------------------- aquatic -- */
  {
    id: 'salmon',
    name: 'Salmon, Atlantic',
    category: 'aquatic',
    tags: ['fish', 'prey-part'],
    source: 'USDA SR Legacy 15236',
    confidence: 'high',
    coverage: 'full',
    g: { water: 64.9, protein: 20.4, fat: 13.4, carb: 0, fiber: 0, ash: 1.1 },
    mg: { sodium: 59, potassium: 363, calcium: 9, magnesium: 27, phosphorus: 240, iron: 0.34, zinc: 0.36, copper: 0.05, vitaminE: 3.55, vitaminB1: 0.21, vitaminB2: 0.16, vitaminB3: 8.0, vitaminB5: 1.55, vitaminB6: 0.64 },
    ug: { selenium: 24, iodine: 15, vitaminA: 17, vitaminD: 11, vitaminB9: 26, vitaminB12: 3.2 },
  },
  {
    id: 'cod',
    name: 'Cod, Atlantic',
    category: 'aquatic',
    tags: ['fish', 'prey-part'],
    source: 'USDA SR Legacy 15015',
    confidence: 'high',
    coverage: 'partial',
    g: { water: 81.2, protein: 17.8, fat: 0.7, carb: 0, fiber: 0, ash: 1.2 },
    mg: { sodium: 54, potassium: 413, calcium: 16, magnesium: 32, phosphorus: 203, iron: 0.38, zinc: 0.45, vitaminB3: 2.06, vitaminB6: 0.24 },
    ug: { selenium: 33.1, iodine: 110, vitaminD: 0.9, vitaminB12: 0.91 },
  },
  {
    id: 'tuna',
    name: 'Tuna, bluefin',
    category: 'aquatic',
    tags: ['fish', 'prey-part'],
    source: 'USDA SR Legacy 15076',
    confidence: 'high',
    coverage: 'partial',
    g: { water: 70.5, protein: 23.3, fat: 4.9, carb: 0, fiber: 0, ash: 1.3 },
    mg: { sodium: 39, potassium: 252, calcium: 8, magnesium: 50, phosphorus: 254, iron: 1.02, zinc: 0.6, vitaminB3: 8.65, vitaminB6: 0.46 },
    ug: { selenium: 36.5, iodine: 14, vitaminA: 655, vitaminD: 5.7, vitaminB12: 9.43 },
  },
  {
    id: 'sardine',
    name: 'Sardine, canned with bones',
    category: 'aquatic',
    tags: ['fish', 'preserved'],
    source: 'USDA SR Legacy 15088',
    confidence: 'high',
    coverage: 'partial',
    note: 'The bones are eaten, which is why the calcium and ash are so high for a fish.',
    g: { water: 59.6, protein: 24.6, fat: 11.5, carb: 0, fiber: 0, ash: 4.3 },
    mg: { sodium: 307, potassium: 397, calcium: 382, magnesium: 39, phosphorus: 490, iron: 2.92, zinc: 1.31, copper: 0.19, vitaminE: 2.04, vitaminB2: 0.23, vitaminB3: 5.24 },
    ug: { selenium: 52.7, iodine: 35, vitaminA: 32, vitaminD: 4.8, vitaminB12: 8.94 },
  },
  {
    id: 'mackerel',
    name: 'Mackerel, Atlantic',
    category: 'aquatic',
    tags: ['fish', 'prey-part'],
    source: 'USDA SR Legacy 15047',
    confidence: 'high',
    coverage: 'partial',
    g: { water: 66.1, protein: 18.6, fat: 13.9, carb: 0, fiber: 0, ash: 1.4 },
    mg: { sodium: 90, potassium: 314, calcium: 12, magnesium: 76, phosphorus: 217, iron: 1.63, zinc: 0.63, vitaminB3: 9.08, vitaminB6: 0.4 },
    ug: { selenium: 44.1, vitaminA: 54, vitaminD: 16.1, vitaminB12: 8.71 },
  },
  {
    id: 'herring',
    name: 'Herring, Atlantic',
    category: 'aquatic',
    tags: ['fish', 'prey-part'],
    source: 'USDA SR Legacy 15040',
    confidence: 'high',
    coverage: 'partial',
    g: { water: 72.0, protein: 18.0, fat: 9.0, carb: 0, fiber: 0, ash: 1.5 },
    mg: { sodium: 90, potassium: 327, calcium: 57, magnesium: 32, phosphorus: 236, iron: 1.1, zinc: 0.99, vitaminB3: 3.22 },
    ug: { selenium: 36.5, vitaminA: 28, vitaminD: 16.1, vitaminB12: 13.67 },
  },
  {
    id: 'trout',
    name: 'Trout, rainbow',
    category: 'aquatic',
    tags: ['fish', 'prey-part'],
    source: 'USDA SR Legacy 15237',
    confidence: 'medium',
    coverage: 'partial',
    g: { water: 71.9, protein: 20.5, fat: 6.2, carb: 0, fiber: 0, ash: 1.2 },
    mg: { sodium: 44, potassium: 417, calcium: 67, magnesium: 31, phosphorus: 271, iron: 0.3, zinc: 0.42, vitaminB3: 5.4 },
    ug: { selenium: 12.6, vitaminD: 13.6, vitaminB12: 4.5 },
  },
  {
    id: 'shrimp',
    name: 'Shrimp',
    category: 'aquatic',
    tags: ['crustacean', 'prey-part'],
    source: 'USDA SR Legacy 15270',
    confidence: 'high',
    coverage: 'partial',
    g: { water: 78.5, protein: 20.1, fat: 0.5, carb: 0.9, fiber: 0, ash: 1.4 },
    mg: { sodium: 148, potassium: 182, calcium: 54, magnesium: 22, phosphorus: 205, iron: 0.21, zinc: 1.34, copper: 0.26, vitaminE: 1.35, vitaminB3: 1.78 },
    ug: { selenium: 29.6, iodine: 35, vitaminA: 54, vitaminD: 0.1, vitaminB12: 1.11 },
  },
  {
    id: 'crab',
    name: 'Crab, blue',
    category: 'aquatic',
    tags: ['crustacean', 'prey-part'],
    source: 'USDA SR Legacy 15139',
    confidence: 'medium',
    coverage: 'partial',
    g: { water: 79.0, protein: 18.1, fat: 1.1, carb: 0, fiber: 0, ash: 1.7 },
    mg: { sodium: 293, potassium: 329, calcium: 89, magnesium: 34, phosphorus: 229, iron: 0.74, zinc: 3.54, copper: 0.68, vitaminB3: 2.8 },
    ug: { selenium: 36.4, iodine: 36, vitaminB12: 9.0 },
  },
  {
    id: 'lobster',
    name: 'Lobster',
    category: 'aquatic',
    tags: ['crustacean', 'prey-part'],
    source: 'USDA SR Legacy 15147',
    confidence: 'medium',
    coverage: 'partial',
    g: { water: 76.8, protein: 19.0, fat: 0.9, carb: 0, fiber: 0, ash: 2.2 },
    mg: { sodium: 423, potassium: 277, calcium: 84, magnesium: 32, phosphorus: 157, iron: 0.29, zinc: 2.48, copper: 1.55 },
    ug: { selenium: 41.4, vitaminB12: 0.95 },
  },
  {
    id: 'mussel',
    name: 'Mussel, blue',
    category: 'aquatic',
    tags: ['mollusc', 'prey-part'],
    source: 'USDA SR Legacy 15164',
    confidence: 'high',
    coverage: 'partial',
    g: { water: 80.6, protein: 11.9, fat: 2.2, carb: 3.7, fiber: 0, ash: 1.6 },
    mg: { sodium: 286, potassium: 320, calcium: 26, magnesium: 34, phosphorus: 197, iron: 3.95, zinc: 1.6, copper: 0.09, manganese: 3.4, vitaminC: 8, vitaminB3: 1.6 },
    ug: { selenium: 44.8, iodine: 140, vitaminA: 48, vitaminB9: 42, vitaminB12: 12 },
  },
  {
    id: 'oyster',
    name: 'Oyster, eastern',
    category: 'aquatic',
    tags: ['mollusc', 'prey-part', 'nutrient-dense'],
    source: 'USDA SR Legacy 15167',
    confidence: 'high',
    coverage: 'full',
    note: 'Zinc content is roughly ten times any other common food.',
    g: { water: 85.1, protein: 7.1, fat: 2.5, carb: 3.9, fiber: 0, ash: 1.4 },
    mg: { sodium: 112, potassium: 156, calcium: 45, magnesium: 47, phosphorus: 135, iron: 5.11, zinc: 39.3, copper: 4.46, manganese: 0.38, vitaminC: 3.7, vitaminE: 0.85, vitaminB2: 0.07, vitaminB3: 1.25 },
    ug: { selenium: 63.7, iodine: 58, vitaminA: 24, vitaminD: 8, vitaminB9: 9, vitaminB12: 16.0 },
  },
  {
    id: 'clam',
    name: 'Clam',
    category: 'aquatic',
    tags: ['mollusc', 'prey-part', 'nutrient-dense'],
    source: 'USDA SR Legacy 15157',
    confidence: 'high',
    coverage: 'partial',
    note: 'The richest ordinary source of cobalamin anywhere in this biosphere.',
    g: { water: 81.8, protein: 12.8, fat: 1.0, carb: 2.6, fiber: 0, ash: 1.8 },
    mg: { sodium: 56, potassium: 314, calcium: 46, magnesium: 9, phosphorus: 169, iron: 13.98, zinc: 1.37, copper: 0.34, manganese: 0.51, vitaminC: 13, vitaminB3: 1.77 },
    ug: { selenium: 24.3, iodine: 90, vitaminA: 90, vitaminB9: 16, vitaminB12: 49.4 },
  },
  {
    id: 'squid',
    name: 'Squid',
    category: 'aquatic',
    tags: ['mollusc', 'prey-part'],
    source: 'USDA SR Legacy 15175',
    confidence: 'medium',
    coverage: 'partial',
    g: { water: 78.6, protein: 15.6, fat: 1.4, carb: 3.1, fiber: 0, ash: 1.4 },
    mg: { sodium: 44, potassium: 246, calcium: 32, magnesium: 33, phosphorus: 221, iron: 0.68, zinc: 1.53, copper: 1.89, vitaminC: 4.7, vitaminB3: 2.18 },
    ug: { selenium: 44.8, vitaminB12: 1.3 },
  },
  {
    id: 'octopus',
    name: 'Octopus',
    category: 'aquatic',
    tags: ['mollusc', 'prey-part'],
    source: 'USDA SR Legacy 15169',
    confidence: 'medium',
    coverage: 'partial',
    g: { water: 80.3, protein: 14.9, fat: 1.0, carb: 2.2, fiber: 0, ash: 1.6 },
    mg: { sodium: 230, potassium: 350, calcium: 53, magnesium: 30, phosphorus: 186, iron: 5.3, zinc: 1.68, copper: 0.43, vitaminC: 5, vitaminB3: 2.1 },
    ug: { selenium: 44.8, vitaminA: 45, vitaminB9: 16, vitaminB12: 20 },
  },

  /* -------------------------------------------------------------- insect -- */
  {
    id: 'cricket',
    name: 'House cricket',
    category: 'insect',
    tags: ['prey-part', 'swarm'],
    source: 'Kulma et al. 2023, dry-matter values rehydrated to 70% moisture',
    confidence: 'medium',
    coverage: 'partial',
    note: 'Fibre here is chitin from the exoskeleton, not plant cellulose, but it behaves the same way: locked until the hive can cleave it.',
    g: { water: 70.0, protein: 19.7, fat: 6.45, carb: 0.19, fiber: 2.21, ash: 1.45 },
    mg: { sodium: 126, potassium: 330, calcium: 42, magnesium: 318, phosphorus: 249, iron: 1.26, zinc: 3.01, copper: 0.97, manganese: 0.57 },
    ug: { molybdenum: 27 },
  },
  {
    id: 'mealworm',
    name: 'Mealworm larva',
    category: 'insect',
    tags: ['prey-part', 'swarm'],
    source: 'Averaged across published feeder-insect analyses',
    confidence: 'medium',
    coverage: 'partial',
    g: { water: 61.9, protein: 18.7, fat: 13.4, carb: 2.4, fiber: 2.5, ash: 1.1 },
    mg: { sodium: 110, potassium: 310, calcium: 42, magnesium: 80, phosphorus: 250, iron: 1.9, zinc: 3.2, copper: 0.7, manganese: 0.35 },
  },
  {
    id: 'locust',
    name: 'Locust',
    category: 'insect',
    tags: ['prey-part', 'swarm'],
    source: 'Averaged across published edible-insect analyses',
    confidence: 'low',
    coverage: 'partial',
    g: { water: 68.0, protein: 20.6, fat: 6.1, carb: 1.0, fiber: 2.9, ash: 1.4 },
    mg: { sodium: 130, potassium: 290, calcium: 36, magnesium: 65, phosphorus: 230, iron: 3.0, zinc: 2.4, copper: 0.6 },
  },
  {
    id: 'silkworm_pupa',
    name: 'Silkworm pupa',
    category: 'insect',
    tags: ['prey-part'],
    source: 'Averaged across published edible-insect analyses',
    confidence: 'low',
    coverage: 'partial',
    g: { water: 70.0, protein: 17.5, fat: 9.0, carb: 0.9, fiber: 1.5, ash: 1.1 },
    mg: { sodium: 50, potassium: 240, calcium: 40, magnesium: 50, phosphorus: 200, iron: 2.5, zinc: 2.0 },
  },
  {
    id: 'soldier_fly_larva',
    name: 'Black soldier fly larva',
    category: 'insect',
    tags: ['prey-part', 'swarm', 'detritivore'],
    source: 'Averaged across published feeder-insect analyses',
    confidence: 'medium',
    coverage: 'partial',
    note: 'Unusually calcium-rich for an insect, which makes it a cheap route to skeletal mineral.',
    g: { water: 61.0, protein: 17.5, fat: 14.0, carb: 1.3, fiber: 2.7, ash: 3.5 },
    mg: { sodium: 130, potassium: 420, calcium: 1000, magnesium: 120, phosphorus: 540, iron: 4.0, zinc: 3.8, manganese: 1.2 },
  },
  {
    id: 'termite',
    name: 'Termite',
    category: 'insect',
    tags: ['prey-part', 'swarm', 'fuel-dense'],
    source: 'Averaged across published edible-insect analyses',
    confidence: 'low',
    coverage: 'partial',
    g: { water: 61.0, protein: 14.2, fat: 20.0, carb: 1.0, fiber: 2.2, ash: 1.6 },
    mg: { sodium: 60, potassium: 220, calcium: 40, magnesium: 40, phosphorus: 180, iron: 3.5, zinc: 2.0 },
  },
  {
    id: 'weaver_ant',
    name: 'Weaver ant',
    category: 'insect',
    tags: ['prey-part', 'swarm'],
    source: 'Averaged across published edible-insect analyses',
    confidence: 'low',
    coverage: 'partial',
    g: { water: 72.0, protein: 13.9, fat: 3.5, carb: 7.0, fiber: 2.1, ash: 1.5 },
    mg: { sodium: 70, potassium: 200, calcium: 48, magnesium: 35, phosphorus: 150, iron: 5.7, zinc: 1.8 },
  },

  /* --------------------------------------------------------- egg & dairy -- */
  {
    id: 'egg_whole',
    name: 'Chicken egg, whole',
    category: 'egg',
    tags: ['bird'],
    source: 'USDA SR Legacy 01123',
    confidence: 'high',
    coverage: 'full',
    g: { water: 76.2, protein: 12.6, fat: 9.5, carb: 0.7, fiber: 0, ash: 1.0 },
    mg: { sodium: 142, potassium: 138, calcium: 56, magnesium: 12, phosphorus: 198, iron: 1.75, zinc: 1.29, copper: 0.07, manganese: 0.03, vitaminE: 1.05, vitaminB2: 0.46, vitaminB3: 0.08, vitaminB5: 1.53, vitaminB6: 0.17 },
    ug: { selenium: 30.7, iodine: 24, vitaminA: 160, vitaminD: 2.0, vitaminK: 0.3, vitaminB7: 20, vitaminB9: 47, vitaminB12: 0.89 },
  },
  {
    id: 'egg_yolk',
    name: 'Egg yolk',
    category: 'egg',
    tags: ['bird', 'nutrient-dense'],
    source: 'USDA SR Legacy 01125',
    confidence: 'high',
    coverage: 'partial',
    g: { water: 52.3, protein: 15.9, fat: 26.5, carb: 3.6, fiber: 0, ash: 1.7 },
    mg: { sodium: 48, potassium: 109, calcium: 129, magnesium: 5, phosphorus: 390, iron: 2.73, zinc: 2.3, copper: 0.08, vitaminE: 2.58, vitaminB2: 0.53, vitaminB5: 2.99, vitaminB6: 0.35 },
    ug: { selenium: 56, vitaminA: 381, vitaminD: 5.4, vitaminK: 0.7, vitaminB7: 55, vitaminB9: 146, vitaminB12: 1.95 },
  },
  {
    id: 'egg_white',
    name: 'Egg white',
    category: 'egg',
    tags: ['bird'],
    source: 'USDA SR Legacy 01124',
    confidence: 'high',
    coverage: 'partial',
    g: { water: 87.6, protein: 10.9, fat: 0.17, carb: 0.73, fiber: 0, ash: 0.6 },
    mg: { sodium: 166, potassium: 163, calcium: 7, magnesium: 11, phosphorus: 15, iron: 0.08, zinc: 0.03, vitaminB2: 0.44 },
    ug: { selenium: 20, vitaminB12: 0.09 },
  },
  {
    id: 'duck_egg',
    name: 'Duck egg',
    category: 'egg',
    tags: ['bird'],
    source: 'USDA SR Legacy 01130',
    confidence: 'medium',
    coverage: 'partial',
    g: { water: 70.8, protein: 12.8, fat: 13.8, carb: 1.4, fiber: 0, ash: 1.1 },
    mg: { sodium: 146, potassium: 222, calcium: 64, magnesium: 17, phosphorus: 220, iron: 3.85, zinc: 1.41, vitaminB2: 0.4 },
    ug: { selenium: 36.4, vitaminA: 194, vitaminD: 4.4, vitaminB9: 80, vitaminB12: 5.4 },
  },
  {
    id: 'milk_whole',
    name: 'Milk, whole',
    category: 'egg',
    tags: ['cattle', 'fluid'],
    source: 'USDA SR Legacy 01211',
    confidence: 'high',
    coverage: 'full',
    g: { water: 88.1, protein: 3.2, fat: 3.3, carb: 4.8, fiber: 0, ash: 0.7 },
    mg: { sodium: 43, potassium: 132, calcium: 113, magnesium: 10, phosphorus: 84, iron: 0.03, zinc: 0.37, copper: 0.01, vitaminC: 0, vitaminB1: 0.05, vitaminB2: 0.17, vitaminB5: 0.36, vitaminB6: 0.04 },
    ug: { selenium: 3.7, iodine: 15, vitaminA: 46, vitaminD: 1.3, vitaminB9: 5, vitaminB12: 0.45 },
  },
  {
    id: 'milk_skim',
    name: 'Milk, skimmed',
    category: 'egg',
    tags: ['cattle', 'fluid'],
    source: 'USDA SR Legacy 01085',
    confidence: 'high',
    coverage: 'partial',
    g: { water: 90.8, protein: 3.4, fat: 0.2, carb: 5.0, fiber: 0, ash: 0.8 },
    mg: { sodium: 42, potassium: 156, calcium: 125, magnesium: 11, phosphorus: 101, zinc: 0.42, vitaminB2: 0.18 },
    ug: { selenium: 3.3, vitaminB12: 0.5 },
  },
  {
    id: 'cheddar',
    name: 'Cheddar cheese',
    category: 'egg',
    tags: ['cattle', 'processed'],
    source: 'USDA SR Legacy 01009',
    confidence: 'high',
    coverage: 'partial',
    g: { water: 37.0, protein: 24.9, fat: 33.1, carb: 1.3, fiber: 0, ash: 3.9 },
    mg: { sodium: 653, potassium: 76, calcium: 721, magnesium: 28, phosphorus: 512, iron: 0.68, zinc: 3.11, copper: 0.03, vitaminE: 0.71, vitaminB2: 0.43, vitaminB5: 0.41 },
    ug: { selenium: 13.9, iodine: 25, vitaminA: 265, vitaminD: 0.6, vitaminK: 2.4, vitaminB9: 27, vitaminB12: 1.1 },
  },
  {
    id: 'mozzarella',
    name: 'Mozzarella',
    category: 'egg',
    tags: ['cattle', 'processed'],
    source: 'USDA SR Legacy 01026',
    confidence: 'medium',
    coverage: 'partial',
    g: { water: 50.0, protein: 22.2, fat: 22.4, carb: 2.2, fiber: 0, ash: 3.3 },
    mg: { sodium: 627, potassium: 76, calcium: 505, magnesium: 20, phosphorus: 354, iron: 0.44, zinc: 2.92, vitaminB2: 0.28 },
    ug: { selenium: 17, vitaminA: 179, vitaminB12: 2.28 },
  },
  {
    id: 'butter',
    name: 'Butter, salted',
    category: 'fat',
    tags: ['cattle', 'processed', 'fuel-dense'],
    source: 'USDA SR Legacy 01001',
    confidence: 'high',
    coverage: 'partial',
    g: { water: 16.2, protein: 0.85, fat: 81.1, carb: 0.06, fiber: 0, ash: 2.1 },
    mg: { sodium: 643, potassium: 24, calcium: 24, magnesium: 2, phosphorus: 24, iron: 0.02, zinc: 0.09, vitaminE: 2.32 },
    ug: { selenium: 1, vitaminA: 684, vitaminD: 1.5, vitaminK: 7, vitaminB12: 0.17 },
  },
  {
    id: 'yogurt_plain',
    name: 'Yogurt, plain whole',
    category: 'egg',
    tags: ['cattle', 'processed'],
    source: 'USDA SR Legacy 01116',
    confidence: 'medium',
    coverage: 'partial',
    g: { water: 87.9, protein: 3.5, fat: 3.3, carb: 4.7, fiber: 0, ash: 0.7 },
    mg: { sodium: 46, potassium: 155, calcium: 121, magnesium: 12, phosphorus: 95, zinc: 0.59, vitaminB2: 0.14 },
    ug: { selenium: 2.2, vitaminA: 27, vitaminB12: 0.37 },
  },
  {
    id: 'cream_heavy',
    name: 'Cream, heavy',
    category: 'fat',
    tags: ['cattle', 'processed'],
    source: 'USDA SR Legacy 01053',
    confidence: 'medium',
    coverage: 'partial',
    g: { water: 57.7, protein: 2.8, fat: 37.0, carb: 2.8, fiber: 0, ash: 0.6 },
    mg: { sodium: 38, potassium: 95, calcium: 65, magnesium: 7, phosphorus: 62, zinc: 0.23 },
    ug: { selenium: 1.8, vitaminA: 411, vitaminD: 1.3, vitaminB12: 0.22 },
  },
  {
    id: 'whey_powder',
    name: 'Whey powder, sweet',
    category: 'refined',
    tags: ['cattle', 'processed'],
    source: 'USDA SR Legacy 01112',
    confidence: 'medium',
    coverage: 'partial',
    g: { water: 3.2, protein: 12.9, fat: 1.1, carb: 74.5, fiber: 0, ash: 8.3 },
    mg: { sodium: 1079, potassium: 2080, calcium: 796, magnesium: 176, phosphorus: 589, iron: 0.88, zinc: 1.97, vitaminB2: 2.21 },
    ug: { selenium: 27.3, vitaminB9: 12, vitaminB12: 2.5 },
  },

  /* ------------------------------------------------------------- hominid -- */
  {
    id: 'hominid_muscle',
    name: 'Hominid skeletal muscle',
    category: 'hominid',
    tags: ['prey-part', 'sapient'],
    source: 'Estimated from mammalian skeletal muscle composition',
    confidence: 'low',
    coverage: 'partial',
    note: 'Compositionally unremarkable — close to lean pork. The locals would object to the comparison.',
    g: { water: 73.0, protein: 20.0, fat: 5.0, carb: 1.0, fiber: 0, ash: 1.0 },
    mg: { sodium: 60, potassium: 340, calcium: 10, magnesium: 25, phosphorus: 200, iron: 1.8, zinc: 2.5, copper: 0.08, vitaminB3: 5.0, vitaminB6: 0.4 },
    ug: { selenium: 18, vitaminB12: 1.0 },
  },
  {
    id: 'hominid_adipose',
    name: 'Hominid adipose tissue',
    category: 'hominid',
    tags: ['prey-part', 'sapient', 'fuel-dense'],
    source: 'Estimated from mammalian adipose composition',
    confidence: 'low',
    coverage: 'macroOnly',
    g: { water: 15.0, protein: 2.0, fat: 82.7, carb: 0, fiber: 0, ash: 0.3 },
    mg: { sodium: 30, potassium: 30, phosphorus: 15 },
  },
  {
    id: 'hominid_liver',
    name: 'Hominid liver',
    category: 'hominid',
    tags: ['prey-part', 'sapient', 'nutrient-dense'],
    source: 'Estimated from mammalian hepatic composition',
    confidence: 'low',
    coverage: 'partial',
    g: { water: 71.0, protein: 19.5, fat: 4.5, carb: 3.6, fiber: 0, ash: 1.4 },
    mg: { sodium: 70, potassium: 300, calcium: 7, magnesium: 20, phosphorus: 350, iron: 6.5, zinc: 4.0, copper: 2.5, vitaminB2: 2.3, vitaminB3: 12.0 },
    ug: { selenium: 35, vitaminA: 4000, vitaminB9: 220, vitaminB12: 30 },
  },
  {
    id: 'hominid_blood',
    name: 'Hominid blood',
    category: 'hominid',
    tags: ['prey-part', 'sapient', 'fluid'],
    source: 'Standard clinical haematology reference values',
    confidence: 'medium',
    coverage: 'partial',
    g: { water: 80.9, protein: 17.3, fat: 0.2, carb: 0.1, fiber: 0, ash: 1.0 },
    mg: { sodium: 230, potassium: 110, calcium: 10, magnesium: 4, phosphorus: 40, chloride: 290, iron: 47, zinc: 0.7, copper: 0.1 },
    ug: { selenium: 12, vitaminB12: 0.5 },
  },
  {
    id: 'hominid_bone',
    name: 'Hominid bone',
    category: 'hominid',
    tags: ['prey-part', 'sapient', 'skeletal'],
    source: 'Estimated from mammalian cortical bone composition',
    confidence: 'low',
    coverage: 'partial',
    note: 'Roughly two thirds hydroxyapatite by mass; the organic third is almost entirely collagen.',
    g: { water: 12.0, protein: 20.0, fat: 5.0, carb: 0, fiber: 0, ash: 63.0 },
    mg: { calcium: 24700, phosphorus: 11500, magnesium: 300, sodium: 500, potassium: 70 },
  },
];
