// Refined foods, fats and oils, and the non-food half of the database:
// minerals, metals, bulk materials and fluids.
//
// A NOTE ON NON-FOOD MATTER
// The hive has seven macro stores and no others, so every substance has to land
// in one of them. Minerals and anything else incombustible go to `ash`, with
// the elemental breakdown carried by the micronutrient fields — a kilogram of
// iron is 1000 g of ash that assays as 1000 g of iron.
//
// Synthetic hydrocarbons (plastics, bitumen, coal, charcoal) are filed under
// `fat`, because fat is the hive's hydrocarbon pool and these burn like one.
// That is a deliberate game abstraction, not a nutritional claim: no Earth
// organism metabolises polyethylene, and every such item is marked
// `confidence: 'model'` so the codex says so out loud.
//
// Lignocellulose (wood, paper, cotton) goes to `fiber`, which is the right
// home for it — it is the same bond chemistry, and it stays locked away until
// the hive researches cellulolysis.

export default [
  /* ---------------------------------------------------------- fat & oil -- */
  {
    id: 'olive_oil',
    name: 'Olive oil',
    category: 'fat',
    tags: ['fuel-dense', 'refined'],
    source: 'USDA SR Legacy 04053',
    confidence: 'high',
    coverage: 'partial',
    g: { water: 0, protein: 0, fat: 100, carb: 0, fiber: 0, ash: 0 },
    mg: { vitaminE: 14.35 },
    ug: { vitaminK: 60.2 },
  },
  {
    id: 'sunflower_oil',
    name: 'Sunflower oil',
    category: 'fat',
    tags: ['fuel-dense', 'refined'],
    source: 'USDA SR Legacy 04506',
    confidence: 'high',
    coverage: 'partial',
    g: { water: 0, protein: 0, fat: 100, carb: 0, fiber: 0, ash: 0 },
    mg: { vitaminE: 41.08 },
    ug: { vitaminK: 5.4 },
  },
  {
    id: 'lard',
    name: 'Lard',
    category: 'fat',
    tags: ['fuel-dense', 'pig'],
    source: 'USDA SR Legacy 04002',
    confidence: 'high',
    coverage: 'partial',
    g: { water: 0, protein: 0, fat: 100, carb: 0, fiber: 0, ash: 0 },
    mg: { vitaminE: 0.6 },
    ug: { vitaminD: 2.5, vitaminA: 0 },
  },
  {
    id: 'tallow',
    name: 'Beef tallow',
    category: 'fat',
    tags: ['fuel-dense', 'cattle', 'prey-part'],
    source: 'USDA SR Legacy 04001',
    confidence: 'high',
    coverage: 'macroOnly',
    g: { water: 0.2, protein: 0, fat: 99.8, carb: 0, fiber: 0, ash: 0 },
    mg: { vitaminE: 2.7 },
  },
  {
    id: 'coconut_oil',
    name: 'Coconut oil',
    category: 'fat',
    tags: ['fuel-dense', 'refined'],
    source: 'USDA SR Legacy 04047',
    confidence: 'high',
    coverage: 'macroOnly',
    g: { water: 0, protein: 0, fat: 100, carb: 0, fiber: 0, ash: 0 },
    mg: { vitaminE: 0.09 },
  },
  {
    id: 'cod_liver_oil',
    name: 'Cod liver oil',
    category: 'fat',
    tags: ['fuel-dense', 'nutrient-dense'],
    source: 'USDA SR Legacy 04589',
    confidence: 'high',
    coverage: 'partial',
    note: 'The most concentrated natural source of vitamins A and D known on this planet.',
    g: { water: 0, protein: 0, fat: 100, carb: 0, fiber: 0, ash: 0 },
    mg: { vitaminE: 1.0 },
    ug: { vitaminA: 30000, vitaminD: 250 },
  },

  /* ------------------------------------------------------------- refined -- */
  {
    id: 'sucrose',
    name: 'Sucrose',
    category: 'refined',
    tags: ['sugar-dense', 'storable'],
    source: 'USDA SR Legacy 19335',
    confidence: 'high',
    coverage: 'full',
    note: 'Pure available carbohydrate. No micronutrients whatsoever — the purest empty fuel the locals produce.',
    g: { water: 0.03, protein: 0, fat: 0, carb: 99.95, fiber: 0, ash: 0.01 },
  },
  {
    id: 'glucose',
    name: 'Glucose',
    category: 'refined',
    tags: ['sugar-dense', 'storable'],
    source: 'Pure compound',
    confidence: 'high',
    coverage: 'full',
    g: { water: 0.1, protein: 0, fat: 0, carb: 99.9, fiber: 0, ash: 0 },
  },
  {
    id: 'honey',
    name: 'Honey',
    category: 'refined',
    tags: ['sugar-dense', 'insect-made'],
    source: 'USDA SR Legacy 19296',
    confidence: 'high',
    coverage: 'partial',
    g: { water: 17.1, protein: 0.3, fat: 0, carb: 82.4, fiber: 0.2, ash: 0.2 },
    mg: { sodium: 4, potassium: 52, calcium: 6, magnesium: 2, phosphorus: 4, iron: 0.42, zinc: 0.22, manganese: 0.08, vitaminC: 0.5 },
    ug: { selenium: 0.8, vitaminB9: 2 },
  },
  {
    id: 'maple_syrup',
    name: 'Maple syrup',
    category: 'refined',
    tags: ['sugar-dense'],
    source: 'USDA SR Legacy 19911',
    confidence: 'medium',
    coverage: 'partial',
    g: { water: 32.4, protein: 0.04, fat: 0.06, carb: 67.1, fiber: 0, ash: 0.4 },
    mg: { sodium: 12, potassium: 212, calcium: 102, magnesium: 21, phosphorus: 2, iron: 0.11, zinc: 1.47, manganese: 2.91 },
    ug: { selenium: 0.6 },
  },
  {
    id: 'dark_chocolate',
    name: 'Dark chocolate, 70%',
    category: 'refined',
    tags: ['fuel-dense', 'nutrient-dense'],
    source: 'USDA SR Legacy 19904',
    confidence: 'medium',
    coverage: 'partial',
    g: { water: 1.4, protein: 7.9, fat: 42.6, carb: 34.9, fiber: 10.9, ash: 2.3 },
    mg: { sodium: 20, potassium: 715, calcium: 73, magnesium: 228, phosphorus: 308, iron: 11.9, zinc: 3.31, copper: 1.77, manganese: 1.95, vitaminE: 0.59, vitaminB3: 1.05 },
    ug: { selenium: 6.8, vitaminA: 2, vitaminK: 7.3, vitaminB9: 12 },
  },
  {
    id: 'beer',
    name: 'Beer',
    category: 'fluid',
    tags: ['fermented'],
    source: 'USDA SR Legacy 14003',
    confidence: 'high',
    coverage: 'partial',
    g: { water: 91.9, protein: 0.46, fat: 0, carb: 3.55, fiber: 0, ethanol: 3.9, ash: 0.16 },
    mg: { sodium: 4, potassium: 27, calcium: 4, magnesium: 6, phosphorus: 14, iron: 0.02, zinc: 0.01, vitaminB2: 0.03, vitaminB3: 0.51 },
    ug: { selenium: 0.6, vitaminB9: 6, vitaminB12: 0.02 },
  },
  {
    id: 'wine_red',
    name: 'Wine, red',
    category: 'fluid',
    tags: ['fermented'],
    source: 'USDA SR Legacy 14096',
    confidence: 'high',
    coverage: 'partial',
    g: { water: 86.5, protein: 0.07, fat: 0, carb: 2.6, fiber: 0, ethanol: 10.6, ash: 0.3 },
    mg: { sodium: 4, potassium: 127, calcium: 8, magnesium: 12, phosphorus: 23, iron: 0.46, zinc: 0.14, manganese: 0.13 },
    ug: { selenium: 0.2, vitaminK: 0.4, vitaminB9: 1 },
  },
  {
    id: 'spirits_40',
    name: 'Distilled spirits, 40% ABV',
    category: 'fluid',
    tags: ['fermented', 'fuel-dense'],
    source: 'USDA SR Legacy 14533',
    confidence: 'high',
    coverage: 'macroOnly',
    note: 'Ethanol carries 29 kJ/g — denser fuel than sugar or protein, and the only one the locals drink for pleasure.',
    g: { water: 66.6, protein: 0, fat: 0, carb: 0, fiber: 0, ethanol: 33.4, ash: 0 },
  },

  /* ------------------------------------------------------------- mineral -- */
  {
    id: 'table_salt',
    name: 'Table salt',
    category: 'mineral',
    tags: ['refined', 'abundant'],
    source: 'Stoichiometric NaCl',
    confidence: 'high',
    coverage: 'full',
    note: 'Pure sodium chloride. Consumes storage, yields zero energy — the clearest demonstration that mass and fuel are different things.',
    g: { water: 0, protein: 0, fat: 0, carb: 0, fiber: 0, ash: 100 },
    mg: { sodium: 39340, chloride: 60660 },
  },
  {
    id: 'limestone',
    name: 'Limestone',
    category: 'mineral',
    tags: ['abundant', 'quarried'],
    source: 'Stoichiometric CaCO₃',
    confidence: 'high',
    coverage: 'full',
    g: { water: 0, protein: 0, fat: 0, carb: 0, fiber: 0, ash: 100 },
    mg: { calcium: 40040, magnesium: 300 },
  },
  {
    id: 'gypsum',
    name: 'Gypsum',
    category: 'mineral',
    tags: ['quarried'],
    source: 'Stoichiometric CaSO₄·2H₂O',
    confidence: 'high',
    coverage: 'full',
    note: 'One fifth water by mass, chemically bound into the crystal.',
    g: { water: 20.9, protein: 0, fat: 0, carb: 0, fiber: 0, ash: 79.1 },
    mg: { calcium: 23280, sulfur: 18620 },
  },
  {
    id: 'apatite',
    name: 'Phosphate rock',
    category: 'mineral',
    tags: ['quarried'],
    source: 'Typical fluorapatite ore assay',
    confidence: 'medium',
    coverage: 'partial',
    note: 'The only concentrated phosphorus source on the surface of this world.',
    g: { water: 0, protein: 0, fat: 0, carb: 0, fiber: 0, ash: 100 },
    mg: { phosphorus: 18000, calcium: 37000 },
  },
  {
    id: 'quartz_sand',
    name: 'Quartz sand',
    category: 'mineral',
    tags: ['abundant'],
    source: 'Stoichiometric SiO₂',
    confidence: 'high',
    coverage: 'full',
    note: 'Silicon is not on the hive’s panel, so this assays as pure inert mass. Abundant and almost useless.',
    g: { water: 0, protein: 0, fat: 0, carb: 0, fiber: 0, ash: 100 },
  },
  {
    id: 'sulfur_native',
    name: 'Sulfur',
    category: 'mineral',
    tags: ['volcanic'],
    source: 'Elemental',
    confidence: 'high',
    coverage: 'full',
    g: { water: 0, protein: 0, fat: 0, carb: 0, fiber: 0, ash: 100 },
    mg: { sulfur: 100000 },
  },
  {
    id: 'magnetite',
    name: 'Magnetite ore',
    category: 'mineral',
    tags: ['ore'],
    source: 'Stoichiometric Fe₃O₄',
    confidence: 'high',
    coverage: 'full',
    g: { water: 0, protein: 0, fat: 0, carb: 0, fiber: 0, ash: 100 },
    mg: { iron: 72360 },
  },
  {
    id: 'clay',
    name: 'Clay',
    category: 'mineral',
    tags: ['abundant'],
    source: 'Typical kaolinite analysis',
    confidence: 'medium',
    coverage: 'partial',
    g: { water: 14.0, protein: 0, fat: 0, carb: 0, fiber: 0, ash: 86.0 },
    mg: { iron: 3000, potassium: 2000, magnesium: 1500, calcium: 1000 },
  },
  {
    id: 'topsoil',
    name: 'Topsoil',
    category: 'mineral',
    tags: ['abundant'],
    source: 'Typical agricultural topsoil analysis',
    confidence: 'low',
    coverage: 'partial',
    g: { water: 20.0, protein: 0.5, fat: 0.2, carb: 0.3, fiber: 5.0, ash: 74.0 },
    mg: { iron: 3000, calcium: 8000, potassium: 6000, magnesium: 4000, phosphorus: 700, manganese: 600, zinc: 60, copper: 20 },
    ug: { selenium: 400, molybdenum: 1000, chromium: 7000 },
  },

  /* --------------------------------------------------------------- metal -- */
  {
    id: 'iron_metal',
    name: 'Iron',
    category: 'metal',
    tags: ['refined'],
    source: 'Elemental',
    confidence: 'high',
    coverage: 'full',
    note: 'A kilogram of iron is a kilogram of iron. No energy, no vitamins, nothing but the element.',
    g: { water: 0, protein: 0, fat: 0, carb: 0, fiber: 0, ash: 100 },
    mg: { iron: 100000 },
  },
  {
    id: 'copper_metal',
    name: 'Copper',
    category: 'metal',
    tags: ['refined'],
    source: 'Elemental',
    confidence: 'high',
    coverage: 'full',
    g: { water: 0, protein: 0, fat: 0, carb: 0, fiber: 0, ash: 100 },
    mg: { copper: 100000 },
  },
  {
    id: 'zinc_metal',
    name: 'Zinc',
    category: 'metal',
    tags: ['refined'],
    source: 'Elemental',
    confidence: 'high',
    coverage: 'full',
    g: { water: 0, protein: 0, fat: 0, carb: 0, fiber: 0, ash: 100 },
    mg: { zinc: 100000 },
  },
  {
    id: 'manganese_metal',
    name: 'Manganese',
    category: 'metal',
    tags: ['refined'],
    source: 'Elemental',
    confidence: 'high',
    coverage: 'full',
    g: { water: 0, protein: 0, fat: 0, carb: 0, fiber: 0, ash: 100 },
    mg: { manganese: 100000 },
  },
  {
    id: 'selenium_metal',
    name: 'Selenium',
    category: 'metal',
    tags: ['refined', 'rare'],
    source: 'Elemental',
    confidence: 'high',
    coverage: 'full',
    g: { water: 0, protein: 0, fat: 0, carb: 0, fiber: 0, ash: 100 },
    mg: { selenium: 100000 },
  },
  {
    id: 'iodine_crystal',
    name: 'Iodine',
    category: 'metal',
    tags: ['refined', 'rare'],
    source: 'Elemental',
    confidence: 'high',
    coverage: 'full',
    g: { water: 0, protein: 0, fat: 0, carb: 0, fiber: 0, ash: 100 },
    mg: { iodine: 100000 },
  },

  /* ------------------------------------------------------------ material -- */
  {
    id: 'wood',
    name: 'Wood',
    category: 'material',
    tags: ['abundant', 'lignocellulose'],
    source: 'Typical air-dried hardwood analysis',
    confidence: 'medium',
    coverage: 'partial',
    note: 'Cellulose, hemicellulose and lignin. Eight kilojoules a gram sitting in every forest, and completely inaccessible until cellulolysis.',
    g: { water: 12.0, protein: 0.2, fat: 0.3, carb: 0, fiber: 87.0, ash: 0.5 },
    mg: { calcium: 150, potassium: 100, magnesium: 40, manganese: 10, iron: 5 },
  },
  {
    id: 'paper',
    name: 'Paper',
    category: 'material',
    tags: ['lignocellulose', 'refined'],
    source: 'Typical bleached pulp analysis',
    confidence: 'medium',
    coverage: 'macroOnly',
    g: { water: 6.0, protein: 0, fat: 0, carb: 0, fiber: 87.0, ash: 7.0 },
    mg: { calcium: 2000 },
  },
  {
    id: 'cotton',
    name: 'Cotton',
    category: 'material',
    tags: ['lignocellulose'],
    source: 'Near-pure cellulose fibre',
    confidence: 'medium',
    coverage: 'macroOnly',
    g: { water: 7.0, protein: 0, fat: 0.5, carb: 0, fiber: 92.0, ash: 0.5 },
  },
  {
    id: 'wool',
    name: 'Wool',
    category: 'material',
    tags: ['keratin', 'sheep'],
    source: 'Typical keratin fibre analysis',
    confidence: 'medium',
    coverage: 'partial',
    note: 'Almost pure keratin, so it reads as protein — but the disulfide cross-links make it very slow to digest.',
    g: { water: 14.0, protein: 84.0, fat: 1.0, carb: 0, fiber: 0, ash: 1.0 },
    mg: { sulfur: 3400, sodium: 100, calcium: 80 },
  },
  {
    id: 'leather',
    name: 'Leather',
    category: 'material',
    tags: ['collagen', 'cattle'],
    source: 'Typical tanned hide analysis',
    confidence: 'low',
    coverage: 'macroOnly',
    g: { water: 14.0, protein: 82.0, fat: 3.0, carb: 0, fiber: 0, ash: 1.0 },
    mg: { calcium: 300, sulfur: 600 },
  },
  {
    id: 'bone_dry',
    name: 'Bone, dried',
    category: 'material',
    tags: ['skeletal', 'prey-part'],
    source: 'Typical mammalian cortical bone analysis',
    confidence: 'medium',
    coverage: 'partial',
    note: 'The densest calcium and phosphorus source a carcass offers, and most predators leave it behind.',
    g: { water: 8.0, protein: 22.0, fat: 8.0, carb: 0, fiber: 0, ash: 62.0 },
    mg: { calcium: 24000, phosphorus: 11000, magnesium: 300, sodium: 500, zinc: 15, iron: 10 },
  },
  {
    id: 'chitin_shell',
    name: 'Chitin shell',
    category: 'material',
    tags: ['prey-part', 'arthropod'],
    source: 'Typical crustacean carapace analysis',
    confidence: 'low',
    coverage: 'partial',
    g: { water: 5.0, protein: 25.0, fat: 0.5, carb: 0, fiber: 25.0, ash: 44.5 },
    mg: { calcium: 17000, phosphorus: 1200, magnesium: 800, sodium: 900 },
  },
  {
    id: 'charcoal',
    name: 'Charcoal',
    category: 'material',
    tags: ['fuel-dense', 'carbon'],
    source: 'Typical hardwood charcoal analysis',
    confidence: 'model',
    coverage: 'macroOnly',
    note: 'Near-pure carbon. Filed under fat because that is the hive’s hydrocarbon pool; no Earth organism actually metabolises it.',
    g: { water: 3.0, protein: 0, fat: 93.0, carb: 0, fiber: 0, ash: 4.0 },
    mg: { calcium: 2000, potassium: 1200 },
  },
  {
    id: 'coal',
    name: 'Coal',
    category: 'material',
    tags: ['fuel-dense', 'carbon', 'mined'],
    source: 'Typical bituminous coal proximate analysis',
    confidence: 'model',
    coverage: 'macroOnly',
    note: 'Filed under fat as a hydrocarbon. Sulfur content is real and is why burning it smells the way it does.',
    g: { water: 5.0, protein: 0, fat: 80.0, carb: 0, fiber: 0, ash: 15.0 },
    mg: { sulfur: 10000, iron: 3000, calcium: 2000 },
  },
  {
    id: 'crude_oil',
    name: 'Crude oil',
    category: 'material',
    tags: ['fuel-dense', 'carbon', 'fluid'],
    source: 'Typical crude petroleum analysis',
    confidence: 'model',
    coverage: 'macroOnly',
    note: 'Ancient biomass, already rendered down. Filed under fat; chemically it is not far off.',
    g: { water: 0.5, protein: 0, fat: 97.7, carb: 0, fiber: 0, ash: 1.8 },
    mg: { sulfur: 1500 },
  },
  {
    id: 'polyethylene',
    name: 'Polyethylene',
    category: 'material',
    tags: ['polymer', 'synthetic'],
    source: 'Stoichiometric (C₂H₄)ₙ',
    confidence: 'model',
    coverage: 'full',
    note: 'A pure hydrocarbon chain, filed under fat. Nothing on this planet digests it, which is becoming the locals’ problem.',
    g: { water: 0, protein: 0, fat: 100, carb: 0, fiber: 0, ash: 0 },
  },
  {
    id: 'pvc',
    name: 'PVC',
    category: 'material',
    tags: ['polymer', 'synthetic'],
    source: 'Stoichiometric (C₂H₃Cl)ₙ',
    confidence: 'model',
    coverage: 'full',
    note: 'Over half chlorine by mass — a genuinely useful chloride source, if the hive can stomach the rest.',
    g: { water: 0, protein: 0, fat: 43.2, carb: 0, fiber: 0, ash: 56.8 },
    mg: { chloride: 56800 },
  },
  {
    id: 'pet_plastic',
    name: 'PET',
    category: 'material',
    tags: ['polymer', 'synthetic'],
    source: 'Stoichiometric (C₁₀H₈O₄)ₙ',
    confidence: 'model',
    coverage: 'full',
    note: 'Oxygenated enough to sit closer to carbohydrate than to fat, so that is where it is filed.',
    g: { water: 0, protein: 0, fat: 0, carb: 100, fiber: 0, ash: 0 },
  },
  {
    id: 'rubber',
    name: 'Natural rubber',
    category: 'material',
    tags: ['polymer'],
    source: 'Stoichiometric polyisoprene with typical additives',
    confidence: 'model',
    coverage: 'macroOnly',
    g: { water: 1.0, protein: 2.0, fat: 92.0, carb: 0, fiber: 0, ash: 5.0 },
    mg: { sulfur: 2000, zinc: 2500 },
  },
  {
    id: 'glass',
    name: 'Glass',
    category: 'material',
    tags: ['synthetic', 'inert'],
    source: 'Typical soda-lime glass composition',
    confidence: 'high',
    coverage: 'partial',
    g: { water: 0, protein: 0, fat: 0, carb: 0, fiber: 0, ash: 100 },
    mg: { sodium: 9600, calcium: 6000, magnesium: 2000 },
  },
  {
    id: 'concrete',
    name: 'Concrete',
    category: 'material',
    tags: ['synthetic', 'abundant'],
    source: 'Typical hardened Portland concrete analysis',
    confidence: 'medium',
    coverage: 'partial',
    g: { water: 5.0, protein: 0, fat: 0, carb: 0, fiber: 0, ash: 95.0 },
    mg: { calcium: 20000, iron: 3000, magnesium: 1500, sulfur: 1000, potassium: 800 },
  },
  {
    id: 'compost',
    name: 'Compost',
    category: 'material',
    tags: ['detritus'],
    source: 'Typical mature garden compost analysis',
    confidence: 'low',
    coverage: 'partial',
    g: { water: 40.0, protein: 2.0, fat: 0.5, carb: 2.0, fiber: 18.0, ash: 37.5 },
    mg: { calcium: 15000, potassium: 8000, iron: 2000, magnesium: 3000, phosphorus: 2500, manganese: 300, zinc: 150, copper: 40 },
  },

  /* --------------------------------------------------------------- fluid -- */
  {
    id: 'fresh_water',
    name: 'Fresh water',
    category: 'fluid',
    tags: ['abundant', 'starter'],
    source: 'Pure H₂O',
    confidence: 'high',
    coverage: 'full',
    g: { water: 100, protein: 0, fat: 0, carb: 0, fiber: 0, ash: 0 },
  },
  {
    id: 'seawater',
    name: 'Seawater',
    category: 'fluid',
    tags: ['abundant', 'marine'],
    source: 'Standard mean ocean composition, 35 PSU',
    confidence: 'high',
    coverage: 'full',
    note: 'Covers seventy percent of this world and dissolves a usable mineral panel. Free sodium, chloride and magnesium at scale.',
    g: { water: 96.5, protein: 0, fat: 0, carb: 0, fiber: 0, ash: 3.5 },
    mg: { sodium: 1080, chloride: 1940, magnesium: 129, sulfur: 90.5, calcium: 41.1, potassium: 39.9 },
    ug: { iodine: 6, iron: 3, zinc: 0.4, copper: 0.3, selenium: 0.2, molybdenum: 10 },
  },
  {
    id: 'urine',
    name: 'Urine',
    category: 'fluid',
    tags: ['detritus', 'sapient'],
    source: 'Typical human urinalysis values',
    confidence: 'medium',
    coverage: 'partial',
    note: 'Dilute, but a reliable and entirely unguarded source of sodium, potassium and phosphorus.',
    g: { water: 95.0, protein: 2.4, fat: 0, carb: 0.1, fiber: 0, ash: 2.5 },
    mg: { sodium: 300, potassium: 150, chloride: 450, phosphorus: 80, sulfur: 90, calcium: 15, magnesium: 8 },
  },
];
