// Wild organisms and materials.
//
// What lives on this planet where nobody is farming it: the open ocean through
// to the abyssal plain, the sea ice, the tundra, the high desert and the canopy.
// These are what make a territory worth holding — a hive that only ever claims
// farmland and suburb never meets most of this.
//
// Confidence varies far more than in the cultivated database and is marked
// honestly per item. Deep-sea and vent organisms in particular have no
// reference composition at all; those are flagged 'model' and say so in their
// source line. They are good enough to play with and should not be cited.
//
// As elsewhere: `carb` is net of fibre, not USDA carbohydrate-by-difference.
//
// See normalize.js for the authoring format.

export default [
  {
    id: 'anchovy',
    name: 'Anchovy',
    category: 'aquatic',
    tags: ['fish', 'pelagic', 'oily'],
    source: 'USDA SR Legacy 174182 (Fish, anchovy, european, raw)',
    confidence: 'high',
    coverage: 'full',
    g: { water: 73.37, protein: 20.35, fat: 4.84, carb: 0, fiber: 0, ash: 1.44 },
    mg: { sodium: 104, potassium: 383, calcium: 147, magnesium: 41, phosphorus: 174, iron: 3.25, zinc: 1.72, copper: 0.211, manganese: 0.07, vitaminE: 0.57, vitaminB1: 0.055, vitaminB2: 0.256, vitaminB3: 14.024, vitaminB5: 0.645, vitaminB6: 0.143 },
    ug: { selenium: 36.5, vitaminA: 15, vitaminK: 0.1, vitaminB9: 9, vitaminB12: 0.62 },
  },
  {
    id: 'sardine_fresh',
    name: 'Sardine (fresh)',
    category: 'aquatic',
    tags: ['fish', 'pelagic', 'oily'],
    source: 'Inferred from USDA SR Legacy 175116 Atlantic herring (clupeid relative); macros set to published fresh Sardina pilchardus',
    confidence: 'low',
    coverage: 'partial',
    g: { water: 71, protein: 20.4, fat: 6.7, carb: 0, fiber: 0, ash: 1.6 },
    mg: { sodium: 95, potassium: 350, calcium: 85, magnesium: 33, phosphorus: 235, iron: 1.4, zinc: 1.1, copper: 0.12, vitaminE: 1.07, vitaminB2: 0.23, vitaminB3: 4.5, vitaminB6: 0.3 },
    ug: { selenium: 36.5, vitaminD: 4.5, vitaminB12: 9 },
  },
  {
    id: 'flying_fish',
    name: 'Flying fish',
    category: 'aquatic',
    tags: ['fish', 'pelagic', 'lean'],
    source: 'Modelled from lean pelagic fish mean (Exocoetidae reported ~21 g protein, ~1 g fat)',
    confidence: 'model',
    coverage: 'macroOnly',
    g: { water: 75.9, protein: 21.2, fat: 1.1, carb: 0, fiber: 0, ash: 1.4 },
  },
  {
    id: 'bonito',
    name: 'Bonito',
    category: 'aquatic',
    tags: ['fish', 'pelagic', 'scombrid'],
    source: 'Inferred from USDA SR Legacy 175156 skipjack tuna; fat/water set to published Sarda sarda',
    confidence: 'low',
    coverage: 'partial',
    g: { water: 71, protein: 23.3, fat: 4, carb: 0, fiber: 0, ash: 1.5 },
    mg: { sodium: 37, potassium: 407, calcium: 29, magnesium: 34, phosphorus: 222, iron: 1.25, zinc: 0.82, copper: 0.086, manganese: 0.015, vitaminB1: 0.033, vitaminB2: 0.1, vitaminB3: 15.4, vitaminB5: 0.42, vitaminB6: 0.85 },
    ug: { selenium: 36.5, vitaminB9: 9, vitaminB12: 1.9 },
  },
  {
    id: 'swordfish',
    name: 'Swordfish',
    category: 'aquatic',
    tags: ['fish', 'pelagic', 'predator'],
    source: 'USDA SR Legacy 173703 (Fish, swordfish, raw)',
    confidence: 'high',
    coverage: 'full',
    g: { water: 73.38, protein: 19.66, fat: 6.65, carb: 0, fiber: 0, ash: 1.44 },
    mg: { sodium: 81, potassium: 418, calcium: 5, magnesium: 29, phosphorus: 255, iron: 0.38, zinc: 0.66, copper: 0.039, manganese: 0.011, vitaminE: 2.02, vitaminB1: 0.075, vitaminB2: 0.053, vitaminB3: 7.76, vitaminB5: 0.35, vitaminB6: 0.543 },
    ug: { selenium: 57.4, vitaminA: 36, vitaminD: 13.9, vitaminK: 0.1, vitaminB9: 2, vitaminB12: 1.7 },
  },
  {
    id: 'marlin',
    name: 'Marlin',
    category: 'aquatic',
    tags: ['fish', 'pelagic', 'predator'],
    source: 'Modelled from USDA SR Legacy 173703 swordfish (billfish relative); leaner published Makaira macros',
    confidence: 'model',
    coverage: 'macroOnly',
    g: { water: 73.3, protein: 22.4, fat: 2.6, carb: 0, fiber: 0, ash: 1.3 },
  },
  {
    id: 'mahi_mahi',
    name: 'Mahi-mahi',
    category: 'aquatic',
    tags: ['fish', 'pelagic', 'lean'],
    source: 'USDA SR Legacy 171959 (Fish, mahimahi, raw)',
    confidence: 'high',
    coverage: 'full',
    g: { water: 77.55, protein: 18.5, fat: 0.7, carb: 0, fiber: 0, ash: 2.1 },
    mg: { sodium: 88, potassium: 416, calcium: 15, magnesium: 30, phosphorus: 143, iron: 1.13, zinc: 0.46, copper: 0.041, manganese: 0.015, vitaminB1: 0.02, vitaminB2: 0.07, vitaminB3: 6.1, vitaminB5: 0.75, vitaminB6: 0.4 },
    ug: { selenium: 36.5, vitaminA: 54, vitaminB9: 5, vitaminB12: 0.6 },
  },
  {
    id: 'blue_whiting',
    name: 'Blue whiting',
    category: 'aquatic',
    tags: ['fish', 'gadoid', 'lean'],
    source: 'USDA SR Legacy 173713 whiting (mixed species) as gadoid proxy for Micromesistius poutassou',
    confidence: 'low',
    coverage: 'full',
    g: { water: 80.27, protein: 18.31, fat: 1.31, carb: 0, fiber: 0, ash: 1.3 },
    mg: { sodium: 72, potassium: 249, calcium: 48, magnesium: 21, phosphorus: 222, iron: 0.34, zinc: 0.88, copper: 0.031, manganese: 0.104, vitaminE: 0.3, vitaminB1: 0.056, vitaminB2: 0.046, vitaminB3: 1.3, vitaminB5: 0.216, vitaminB6: 0.156 },
    ug: { selenium: 32.1, vitaminA: 30, vitaminD: 1.4, vitaminK: 0.1, vitaminB9: 13, vitaminB12: 2.3 },
  },
  {
    id: 'capelin',
    name: 'Capelin',
    category: 'aquatic',
    tags: ['fish', 'forage-fish', 'oily'],
    source: 'Inferred from USDA SR Legacy 175146 rainbow smelt (Osmeridae relative); fat raised to published Mallotus villosus',
    confidence: 'low',
    coverage: 'partial',
    g: { water: 74.5, protein: 16.5, fat: 7, carb: 0, fiber: 0, ash: 2 },
    mg: { sodium: 60, potassium: 290, calcium: 60, magnesium: 30, phosphorus: 230, iron: 0.9, zinc: 1.65, copper: 0.139, manganese: 0.7, vitaminB2: 0.12, vitaminB3: 1.45 },
    ug: { selenium: 36.5, vitaminD: 0.8, vitaminB12: 3.44 },
  },
  {
    id: 'menhaden',
    name: 'Menhaden',
    category: 'aquatic',
    tags: ['fish', 'forage-fish', 'oily'],
    source: 'Modelled from clupeid whole-fish mean (Brevoortia reported 9-13 g fat)',
    confidence: 'model',
    coverage: 'macroOnly',
    g: { water: 68, protein: 18.5, fat: 10.5, carb: 0, fiber: 0, ash: 2.5 },
  },
  {
    id: 'krill_antarctic',
    name: 'Antarctic krill',
    category: 'aquatic',
    tags: ['crustacean', 'zooplankton', 'prey-part'],
    source: 'Published Euphausia superba proximate means (Sidhu 1970; Fisheries & Aquatic Sci. 2014)',
    confidence: 'medium',
    coverage: 'macroOnly',
    g: { water: 79.9, protein: 13.3, fat: 3.1, carb: 0.7, fiber: 0.9, ash: 3 },
  },
  {
    id: 'copepod_mass',
    name: 'Copepod mass',
    category: 'aquatic',
    tags: ['zooplankton', 'prey-part', 'wax-ester'],
    source: 'Modelled from Calanus finmarchicus literature (high wax-ester lipid, 10-25% WW)',
    confidence: 'model',
    coverage: 'macroOnly',
    g: { water: 73, protein: 11, fat: 13, carb: 0.5, fiber: 0.8, ash: 2 },
  },
  {
    id: 'salp',
    name: 'Salp',
    category: 'aquatic',
    tags: ['gelatinous', 'zooplankton'],
    source: 'Modelled from Thaliacea literature (>95% water, trace organics, high ash)',
    confidence: 'model',
    coverage: 'macroOnly',
    g: { water: 95, protein: 1.3, fat: 0.2, carb: 0.4, fiber: 0, ash: 3 },
  },
  {
    id: 'jellyfish_dried',
    name: 'Jellyfish (dried, salted)',
    category: 'aquatic',
    tags: ['gelatinous', 'preserved', 'high-sodium'],
    source: 'USDA SR Legacy 168129 (Jellyfish, dried, salted)',
    confidence: 'high',
    coverage: 'full',
    g: { water: 68, protein: 5.5, fat: 1.4, carb: 0, fiber: 0, ash: 25.1 },
    mg: { sodium: 9690, potassium: 3, calcium: 2, magnesium: 2, phosphorus: 20, iron: 2.27, zinc: 0.42, copper: 0.14, vitaminE: 0.02, vitaminB1: 0.01, vitaminB2: 0.01, vitaminB3: 0.2, vitaminB6: 0.01 },
    ug: { selenium: 42.2, vitaminA: 2, vitaminK: 0.1, vitaminB9: 1, vitaminB12: 0.02 },
  },
  {
    id: 'albacore',
    name: 'Albacore',
    category: 'aquatic',
    tags: ['fish', 'pelagic', 'scombrid'],
    source: 'Inferred from USDA SR Legacy 173706 fresh bluefin tuna (Thunnus relative); macros set to published albacore',
    confidence: 'low',
    coverage: 'partial',
    g: { water: 68.5, protein: 25, fat: 4.9, carb: 0, fiber: 0, ash: 1.3 },
    mg: { sodium: 39, potassium: 252, calcium: 8, magnesium: 50, phosphorus: 254, iron: 1.02, zinc: 0.6, copper: 0.086, manganese: 0.015, vitaminE: 1, vitaminB1: 0.241, vitaminB2: 0.251, vitaminB3: 8.654, vitaminB5: 1.054, vitaminB6: 0.455 },
    ug: { selenium: 36.5, vitaminD: 5.7, vitaminB9: 2, vitaminB12: 9.43 },
  },
  {
    id: 'lanternfish',
    name: 'Lanternfish',
    category: 'aquatic',
    tags: ['fish', 'mesopelagic', 'wax-ester'],
    source: 'Published myctophid ranges (Sustainability 2023, 15:12039): protein 11-23 g, lipid 0.5-26 g WW; midpoint taken',
    confidence: 'medium',
    coverage: 'partial',
    g: { water: 72, protein: 14.5, fat: 9, carb: 0, fiber: 0, ash: 3 },
    ug: { vitaminA: 100, vitaminB12: 6.2 },
  },
  {
    id: 'hatchetfish',
    name: 'Hatchetfish',
    category: 'aquatic',
    tags: ['fish', 'mesopelagic', 'wax-ester'],
    source: 'Modelled from mesopelagic fish mean (high water, moderate wax-ester lipid)',
    confidence: 'model',
    coverage: 'macroOnly',
    g: { water: 78, protein: 12, fat: 6.5, carb: 0, fiber: 0, ash: 2.8 },
  },
  {
    id: 'bristlemouth',
    name: 'Bristlemouth',
    category: 'aquatic',
    tags: ['fish', 'mesopelagic'],
    source: 'Modelled from Cyclothone literature (very watery, low lipid mesopelagic)',
    confidence: 'model',
    coverage: 'macroOnly',
    g: { water: 82, protein: 10.5, fat: 4, carb: 0, fiber: 0, ash: 2.6 },
  },
  {
    id: 'viperfish',
    name: 'Viperfish',
    category: 'aquatic',
    tags: ['fish', 'mesopelagic', 'predator'],
    source: 'Modelled from mesopelagic predator mean (Chauliodus); wax-ester rich',
    confidence: 'model',
    coverage: 'macroOnly',
    g: { water: 79, protein: 13, fat: 5, carb: 0, fiber: 0, ash: 2.6 },
  },
  {
    id: 'humboldt_squid',
    name: 'Humboldt squid',
    category: 'aquatic',
    tags: ['cephalopod', 'mesopelagic'],
    source: 'Inferred from USDA SR Legacy 174223 squid (mixed species); macros set to published Dosidicus gigas',
    confidence: 'low',
    coverage: 'partial',
    g: { water: 81.5, protein: 15.5, fat: 1, carb: 0.5, fiber: 0, ash: 1.5 },
    mg: { sodium: 44, potassium: 246, calcium: 32, magnesium: 33, phosphorus: 221, iron: 0.68, zinc: 1.53, copper: 1.891, manganese: 0.035, vitaminB2: 0.412, vitaminB3: 2.175 },
    ug: { selenium: 44.8, vitaminB12: 1.3 },
  },
  {
    id: 'vampire_squid',
    name: 'Vampire squid',
    category: 'aquatic',
    tags: ['cephalopod', 'mesopelagic', 'gelatinous'],
    source: 'Modelled from gelatinous deep-sea cephalopod mean (Vampyroteuthis, ammoniacal/watery tissue)',
    confidence: 'model',
    coverage: 'macroOnly',
    g: { water: 88, protein: 7, fat: 2, carb: 0.5, fiber: 0, ash: 2 },
  },
  {
    id: 'krill_deep',
    name: 'Deep krill',
    category: 'aquatic',
    tags: ['crustacean', 'mesopelagic', 'zooplankton'],
    source: 'Modelled from Thysanoessa/E. crystallorophias literature, reasoned from Antarctic krill with higher lipid',
    confidence: 'model',
    coverage: 'macroOnly',
    g: { water: 78, protein: 12.5, fat: 5.5, carb: 0.6, fiber: 0.8, ash: 2.8 },
  },
  {
    id: 'grenadier',
    name: 'Grenadier (rattail)',
    category: 'aquatic',
    tags: ['fish', 'deep-sea', 'lean'],
    source: 'Published deep-sea macrourid muscle composition (Coryphaenoides/Macrourus: very high water, low protein)',
    confidence: 'medium',
    coverage: 'macroOnly',
    g: { water: 86.5, protein: 11, fat: 0.8, carb: 0, fiber: 0, ash: 1.2 },
  },
  {
    id: 'deepsea_anglerfish',
    name: 'Deep-sea anglerfish',
    category: 'aquatic',
    tags: ['fish', 'deep-sea', 'gelatinous'],
    source: 'Modelled from abyssal teleost mean (watery, low-protein muscle)',
    confidence: 'model',
    coverage: 'macroOnly',
    g: { water: 87, protein: 10, fat: 1.2, carb: 0, fiber: 0, ash: 1.3 },
  },
  {
    id: 'sea_cucumber',
    name: 'Sea cucumber',
    category: 'aquatic',
    tags: ['echinoderm', 'benthic'],
    source: 'USDA SR Legacy 167618 (Sea cucumber, yane, Alaska Native); carb 2.6 g added by difference',
    confidence: 'medium',
    coverage: 'partial',
    g: { water: 80.7, protein: 13, fat: 0.4, carb: 2.6, fiber: 0, ash: 2.8 },
    mg: { calcium: 30, iron: 0.6, vitaminB1: 0.05, vitaminB2: 0.94, vitaminB3: 3.2 },
  },
  {
    id: 'brittle_star',
    name: 'Abyssal brittle star',
    category: 'aquatic',
    tags: ['echinoderm', 'benthic', 'calcified'],
    source: 'Modelled from calcified echinoderm whole-body mean (calcite ossicles dominate ash)',
    confidence: 'model',
    coverage: 'macroOnly',
    g: { water: 68, protein: 8, fat: 1.5, carb: 1, fiber: 0, ash: 21 },
  },
  {
    id: 'giant_isopod',
    name: 'Giant isopod',
    category: 'aquatic',
    tags: ['crustacean', 'deep-sea', 'chitinous'],
    source: 'Modelled from large benthic crustacean mean (Bathynomus; heavy mineralised cuticle)',
    confidence: 'model',
    coverage: 'macroOnly',
    g: { water: 74, protein: 14, fat: 1.5, carb: 0.5, fiber: 1.5, ash: 8 },
  },
  {
    id: 'sleeper_shark',
    name: 'Sleeper shark flesh',
    category: 'aquatic',
    tags: ['elasmobranch', 'deep-sea', 'urea-rich'],
    source: 'USDA SR Legacy 173697 shark (mixed species) as proxy for Somniosus',
    confidence: 'low',
    coverage: 'full',
    g: { water: 73.58, protein: 20.98, fat: 4.51, carb: 0, fiber: 0, ash: 1.39 },
    mg: { sodium: 79, potassium: 160, calcium: 34, magnesium: 49, phosphorus: 210, iron: 0.84, zinc: 0.43, copper: 0.033, manganese: 0.015, vitaminE: 1, vitaminB1: 0.042, vitaminB2: 0.062, vitaminB3: 2.938, vitaminB5: 0.695, vitaminB6: 0.4 },
    ug: { selenium: 36.5, vitaminA: 70, vitaminD: 0.6, vitaminK: 0.1, vitaminB9: 3, vitaminB12: 1.49 },
  },
  {
    id: 'whale_fall_blubber',
    name: 'Whale fall blubber',
    category: 'fat',
    tags: ['blubber', 'marine-mammal'],
    source: 'USDA SR Legacy 167623 (Whale, bowhead, subcutaneous fat/blubber, Alaska Native)',
    confidence: 'high',
    coverage: 'partial',
    g: { water: 2.9, protein: 0.4, fat: 96.5, carb: 0, fiber: 0, ash: 0.2 },
    mg: { phosphorus: 5, iron: 0.5 },
  },
  {
    id: 'whale_bone',
    name: 'Whale bone',
    category: 'material',
    tags: ['bone', 'lipid-rich', 'inedible-raw'],
    source: 'Modelled from cetacean cancellous bone literature (lipid-rich marrow, apatite ash ~45-50%)',
    confidence: 'model',
    coverage: 'macroOnly',
    g: { water: 8, protein: 20, fat: 24, carb: 0, fiber: 0, ash: 48 },
  },
  {
    id: 'tube_worm',
    name: 'Vent tube worm',
    category: 'aquatic',
    tags: ['annelid', 'hydrothermal', 'chemosynthetic'],
    source: 'Modelled from Riftia pachyptila tissue literature (watery vestimentiferan trophosome/plume)',
    confidence: 'model',
    coverage: 'macroOnly',
    g: { water: 85, protein: 10.5, fat: 1, carb: 0.5, fiber: 0.5, ash: 2.5 },
  },
  {
    id: 'vent_shrimp',
    name: 'Vent shrimp',
    category: 'aquatic',
    tags: ['crustacean', 'hydrothermal', 'chemosynthetic'],
    source: 'Modelled from Rimicaris exoculata, reasoned from shallow caridean shrimp',
    confidence: 'model',
    coverage: 'macroOnly',
    g: { water: 77, protein: 15.5, fat: 1.5, carb: 0.5, fiber: 1, ash: 4.5 },
  },
  {
    id: 'vent_mussel',
    name: 'Vent mussel',
    category: 'aquatic',
    tags: ['mollusc', 'hydrothermal', 'chemosynthetic'],
    source: 'Inferred from USDA SR Legacy 174216 blue mussel; Bathymodiolus reported leaner and wetter',
    confidence: 'low',
    coverage: 'macroOnly',
    g: { water: 80, protein: 10, fat: 2, carb: 3, fiber: 0, ash: 4.5 },
  },
  {
    id: 'bacterial_mat',
    name: 'Chemosynthetic bacterial mat',
    category: 'aquatic',
    tags: ['microbial', 'chemosynthetic'],
    source: 'Modelled from sulphur-oxidising bacterial mat literature (Beggiatoa; mostly water, elemental sulphur in ash)',
    confidence: 'model',
    coverage: 'macroOnly',
    g: { water: 88, protein: 6, fat: 1, carb: 2, fiber: 0, ash: 3 },
  },
  {
    id: 'parrotfish',
    name: 'Parrotfish',
    category: 'aquatic',
    tags: ['fish', 'reef', 'lean'],
    source: 'Modelled from USDA SR Legacy 171962 grouper (reef teleost mean); published Scaridae macros',
    confidence: 'low',
    coverage: 'macroOnly',
    g: { water: 77.6, protein: 19.5, fat: 1.2, carb: 0, fiber: 0, ash: 1.3 },
  },
  {
    id: 'grouper',
    name: 'Grouper',
    category: 'aquatic',
    tags: ['fish', 'reef', 'predator'],
    source: 'USDA SR Legacy 171962 (Fish, grouper, mixed species, raw)',
    confidence: 'high',
    coverage: 'full',
    g: { water: 79.22, protein: 19.38, fat: 1.02, carb: 0, fiber: 0, ash: 1.17 },
    mg: { sodium: 53, potassium: 483, calcium: 27, magnesium: 31, phosphorus: 162, iron: 0.89, zinc: 0.48, copper: 0.02, manganese: 0.014, vitaminB1: 0.07, vitaminB2: 0.005, vitaminB3: 0.313, vitaminB5: 0.75, vitaminB6: 0.3 },
    ug: { selenium: 36.5, vitaminA: 43, vitaminB9: 9, vitaminB12: 0.6 },
  },
  {
    id: 'snapper',
    name: 'Snapper',
    category: 'aquatic',
    tags: ['fish', 'reef'],
    source: 'USDA SR Legacy 173698 (Fish, snapper, mixed species, raw)',
    confidence: 'high',
    coverage: 'full',
    g: { water: 76.87, protein: 20.51, fat: 1.34, carb: 0, fiber: 0, ash: 1.31 },
    mg: { sodium: 64, potassium: 417, calcium: 32, magnesium: 32, phosphorus: 198, iron: 0.18, zinc: 0.36, copper: 0.028, manganese: 0.013, vitaminE: 0.96, vitaminB1: 0.046, vitaminB2: 0.003, vitaminB3: 0.284, vitaminB5: 0.75, vitaminB6: 0.4, vitaminC: 1.6 },
    ug: { selenium: 38.2, vitaminA: 32, vitaminD: 10.2, vitaminK: 0.1, vitaminB9: 5, vitaminB12: 3 },
  },
  {
    id: 'sea_urchin_roe',
    name: 'Sea urchin roe',
    category: 'aquatic',
    tags: ['echinoderm', 'roe', 'reef'],
    source: 'Separations 2021, 8:174 (Strongylocentrotus intermedius gonad, fresh)',
    confidence: 'medium',
    coverage: 'macroOnly',
    g: { water: 73, protein: 13.9, fat: 7.3, carb: 3.5, fiber: 0, ash: 2.3 },
  },
  {
    id: 'abalone',
    name: 'Abalone',
    category: 'aquatic',
    tags: ['mollusc', 'reef', 'grazer'],
    source: 'USDA SR Legacy 174212 (Mollusks, abalone, mixed species, raw)',
    confidence: 'high',
    coverage: 'full',
    g: { water: 74.56, protein: 17.1, fat: 0.76, carb: 6.01, fiber: 0, ash: 1.57 },
    mg: { sodium: 301, potassium: 250, calcium: 31, magnesium: 48, phosphorus: 190, iron: 3.19, zinc: 0.82, copper: 0.196, manganese: 0.04, vitaminB1: 0.19, vitaminB2: 0.1, vitaminB3: 1.5, vitaminB5: 3, vitaminB6: 0.15, vitaminC: 2 },
    ug: { selenium: 44.8, vitaminB9: 5, vitaminB12: 0.73 },
  },
  {
    id: 'giant_clam',
    name: 'Giant clam',
    category: 'aquatic',
    tags: ['mollusc', 'reef'],
    source: 'Inferred from USDA SR Legacy 174214 clam (mixed species); published Tridacna macros',
    confidence: 'low',
    coverage: 'macroOnly',
    g: { water: 79, protein: 13.5, fat: 0.8, carb: 3.3, fiber: 0, ash: 2.3 },
  },
  {
    id: 'kelp_fresh',
    name: 'Kelp (fresh)',
    category: 'algae',
    tags: ['seaweed', 'brown-algae', 'high-ash'],
    source: 'USDA SR Legacy 168457 (Seaweed, kelp, raw); carb restated net of fibre',
    confidence: 'high',
    coverage: 'full',
    g: { water: 81.58, protein: 1.68, fat: 0.56, carb: 8.27, fiber: 1.3, ash: 6.61 },
    mg: { sodium: 233, potassium: 89, calcium: 168, magnesium: 121, phosphorus: 42, iron: 2.85, zinc: 1.23, copper: 0.13, manganese: 0.2, vitaminE: 0.87, vitaminB1: 0.05, vitaminB2: 0.15, vitaminB3: 0.47, vitaminB5: 0.642, vitaminB6: 0.002, vitaminC: 3 },
    ug: { selenium: 0.7, vitaminA: 6, vitaminK: 66, vitaminB9: 180 },
  },
  {
    id: 'sea_lettuce',
    name: 'Sea lettuce',
    category: 'algae',
    tags: ['seaweed', 'green-algae'],
    source: 'Modelled from Ulva lactuca literature (dry-basis protein 8-20%, ash 15-25%) rehydrated to fresh thallus',
    confidence: 'low',
    coverage: 'macroOnly',
    g: { water: 85, protein: 2.5, fat: 0.3, carb: 5.5, fiber: 2.5, ash: 4.2 },
  },
  {
    id: 'bladderwrack',
    name: 'Bladderwrack (dried)',
    category: 'algae',
    tags: ['seaweed', 'brown-algae', 'high-iodine'],
    source: 'Fucus vesiculosus literature means (ash 18-25% dry; iodine 150-600 mg/kg dry)',
    confidence: 'low',
    coverage: 'partial',
    g: { water: 12, protein: 8, fat: 2.5, carb: 30, fiber: 26, ash: 21 },
    ug: { iodine: 30000 },
  },
  {
    id: 'irish_moss',
    name: 'Irish moss (carrageen)',
    category: 'algae',
    tags: ['seaweed', 'red-algae'],
    source: 'USDA SR Legacy 168456 (Seaweed, irishmoss, raw); carb restated net of fibre',
    confidence: 'high',
    coverage: 'full',
    g: { water: 81.34, protein: 1.51, fat: 0.16, carb: 10.99, fiber: 1.3, ash: 4.7 },
    mg: { sodium: 67, potassium: 63, calcium: 72, magnesium: 144, phosphorus: 157, iron: 8.9, zinc: 1.95, copper: 0.149, manganese: 0.37, vitaminB1: 0.015, vitaminB2: 0.466, vitaminB3: 0.593, vitaminB5: 0.176, vitaminB6: 0.069, vitaminC: 3 },
    ug: { selenium: 0.7, vitaminB9: 182 },
  },
  {
    id: 'coral_polyp',
    name: 'Coral polyp tissue',
    category: 'aquatic',
    tags: ['cnidarian', 'reef', 'prey-part'],
    source: 'Modelled from scleractinian polyp tissue literature (symbiont-bearing soft tissue, skeleton excluded)',
    confidence: 'model',
    coverage: 'macroOnly',
    g: { water: 83, protein: 7.5, fat: 2.5, carb: 1.5, fiber: 0, ash: 5.5 },
  },
  {
    id: 'sponge',
    name: 'Sponge',
    category: 'aquatic',
    tags: ['sponge', 'reef', 'spongin'],
    source: 'Modelled from demosponge tissue literature (spongin fibre and spicule ash)',
    confidence: 'model',
    coverage: 'macroOnly',
    g: { water: 82, protein: 8, fat: 1.5, carb: 1, fiber: 2, ash: 5.5 },
  },
  {
    id: 'halibut',
    name: 'Halibut',
    category: 'aquatic',
    tags: ['fish', 'flatfish', 'demersal'],
    source: 'USDA SR Legacy 174200 (Fish, halibut, Atlantic and Pacific, raw)',
    confidence: 'high',
    coverage: 'full',
    g: { water: 80.34, protein: 18.56, fat: 1.33, carb: 0, fiber: 0, ash: 1.29 },
    mg: { sodium: 68, potassium: 435, calcium: 7, magnesium: 23, phosphorus: 236, iron: 0.16, zinc: 0.36, copper: 0.023, manganese: 0.011, vitaminE: 0.61, vitaminB1: 0.05, vitaminB2: 0.03, vitaminB3: 6.513, vitaminB5: 0.343, vitaminB6: 0.548 },
    ug: { selenium: 45.6, vitaminA: 20, vitaminD: 4.7, vitaminB9: 12, vitaminB12: 1.1 },
  },
  {
    id: 'plaice_flounder',
    name: 'Plaice / flounder',
    category: 'aquatic',
    tags: ['fish', 'flatfish', 'demersal'],
    source: 'USDA SR Legacy 174196 (Fish, flatfish, flounder and sole species, raw)',
    confidence: 'high',
    coverage: 'full',
    g: { water: 84.63, protein: 12.41, fat: 1.93, carb: 0, fiber: 0, ash: 1.22 },
    mg: { sodium: 296, potassium: 160, calcium: 21, magnesium: 18, phosphorus: 252, iron: 0.18, zinc: 0.32, copper: 0.019, manganese: 0.014, vitaminE: 0.63, vitaminB1: 0.022, vitaminB2: 0.02, vitaminB3: 1.04, vitaminB5: 0.185, vitaminB6: 0.098 },
    ug: { selenium: 26.6, vitaminA: 10, vitaminD: 2.8, vitaminK: 0.1, vitaminB9: 5, vitaminB12: 1.13 },
  },
  {
    id: 'sole',
    name: 'Sole',
    category: 'aquatic',
    tags: ['fish', 'flatfish', 'demersal'],
    source: 'USDA SR Legacy 174196 (same flounder-and-sole row); macros nudged to published Solea solea',
    confidence: 'low',
    coverage: 'partial',
    g: { water: 81.5, protein: 15.6, fat: 1.4, carb: 0, fiber: 0, ash: 1.25 },
    mg: { sodium: 180, potassium: 250, calcium: 21, magnesium: 18, phosphorus: 250, iron: 0.2, zinc: 0.32, vitaminB3: 1.04, vitaminB6: 0.098 },
    ug: { selenium: 26.6, vitaminD: 2.8, vitaminB12: 1.13 },
  },
  {
    id: 'monkfish',
    name: 'Monkfish',
    category: 'aquatic',
    tags: ['fish', 'demersal', 'lean'],
    source: 'USDA SR Legacy 173676 (Fish, monkfish, raw)',
    confidence: 'high',
    coverage: 'full',
    g: { water: 83.24, protein: 14.48, fat: 1.52, carb: 0, fiber: 0, ash: 1.21 },
    mg: { sodium: 18, potassium: 400, calcium: 8, magnesium: 21, phosphorus: 200, iron: 0.32, zinc: 0.41, copper: 0.028, manganese: 0.024, vitaminB1: 0.025, vitaminB2: 0.06, vitaminB3: 2.1, vitaminB5: 0.15, vitaminB6: 0.24, vitaminC: 1 },
    ug: { selenium: 36.5, vitaminA: 12, vitaminB9: 7, vitaminB12: 0.9 },
  },
  {
    id: 'skate_wing',
    name: 'Skate wing',
    category: 'aquatic',
    tags: ['elasmobranch', 'demersal', 'urea-rich'],
    source: 'Modelled from published Raja wing muscle (lean, urea-bearing elasmobranch)',
    confidence: 'model',
    coverage: 'macroOnly',
    g: { water: 79, protein: 19.5, fat: 0.7, carb: 0, fiber: 0, ash: 1.3 },
  },
  {
    id: 'scallop',
    name: 'Scallop',
    category: 'aquatic',
    tags: ['mollusc', 'bivalve', 'benthic'],
    source: 'USDA SR Legacy 174220 (Mollusks, scallop, mixed species, raw)',
    confidence: 'high',
    coverage: 'full',
    g: { water: 82.53, protein: 12.06, fat: 0.49, carb: 3.18, fiber: 0, ash: 1.74 },
    mg: { sodium: 392, potassium: 205, calcium: 6, magnesium: 22, phosphorus: 334, iron: 0.38, zinc: 0.91, copper: 0.023, manganese: 0.017, vitaminB1: 0.007, vitaminB2: 0.015, vitaminB3: 0.703, vitaminB5: 0.215, vitaminB6: 0.073 },
    ug: { selenium: 12.8, vitaminB9: 16, vitaminB12: 1.41 },
  },
  {
    id: 'whelk',
    name: 'Whelk',
    category: 'aquatic',
    tags: ['mollusc', 'gastropod', 'benthic'],
    source: 'USDA SR Legacy 171983 (Mollusks, whelk, unspecified, raw)',
    confidence: 'high',
    coverage: 'full',
    g: { water: 66, protein: 23.84, fat: 0.4, carb: 7.76, fiber: 0, ash: 2 },
    mg: { sodium: 206, potassium: 347, calcium: 57, magnesium: 86, phosphorus: 141, iron: 5.03, zinc: 1.63, copper: 1.03, manganese: 0.447, vitaminB1: 0.026, vitaminB2: 0.107, vitaminB3: 1.05, vitaminB5: 0.208, vitaminB6: 0.342, vitaminC: 4 },
    ug: { selenium: 44.8, vitaminB9: 6, vitaminB12: 9.07 },
  },
  {
    id: 'cockle',
    name: 'Cockle',
    category: 'aquatic',
    tags: ['mollusc', 'bivalve', 'benthic'],
    source: 'USDA SR Legacy 169803 (Cockles, raw, Alaska Native)',
    confidence: 'high',
    coverage: 'partial',
    g: { water: 78.8, protein: 13.5, fat: 0.7, carb: 4.7, fiber: 0, ash: 2.3 },
    mg: { calcium: 30, iron: 16.2, vitaminB1: 0.01, vitaminB2: 0.2, vitaminB3: 3.2 },
  },
  {
    id: 'razor_clam',
    name: 'Razor clam',
    category: 'aquatic',
    tags: ['mollusc', 'bivalve', 'benthic'],
    source: 'Inferred from USDA SR Legacy 174214 clam (mixed species); published Ensis macros',
    confidence: 'low',
    coverage: 'macroOnly',
    g: { water: 79, protein: 14.5, fat: 0.9, carb: 3.3, fiber: 0, ash: 2 },
  },
  {
    id: 'brown_crab',
    name: 'Brown crab',
    category: 'aquatic',
    tags: ['crustacean', 'benthic'],
    source: 'Published Cancer pagurus white meat (Heliyon 2016 comparative crab study)',
    confidence: 'medium',
    coverage: 'macroOnly',
    g: { water: 79, protein: 18.5, fat: 1, carb: 0, fiber: 0, ash: 1.9 },
  },
  {
    id: 'langoustine',
    name: 'Langoustine',
    category: 'aquatic',
    tags: ['crustacean', 'benthic'],
    source: 'Inferred from USDA SR Legacy 174208 northern lobster; published Nephrops norvegicus macros',
    confidence: 'low',
    coverage: 'macroOnly',
    g: { water: 78.5, protein: 18, fat: 0.8, carb: 0.5, fiber: 0, ash: 1.6 },
  },
  {
    id: 'sand_eel',
    name: 'Sand eel',
    category: 'aquatic',
    tags: ['fish', 'forage-fish', 'oily'],
    source: 'Modelled from Ammodytes literature (small oily forage fish, seasonal fat 4-12%)',
    confidence: 'model',
    coverage: 'macroOnly',
    g: { water: 73, protein: 17, fat: 7.5, carb: 0, fiber: 0, ash: 2 },
  },
  {
    id: 'pollock',
    name: 'Pollock',
    category: 'aquatic',
    tags: ['fish', 'gadoid', 'lean'],
    source: 'USDA SR Legacy 175129 (Fish, pollock, Atlantic, raw)',
    confidence: 'high',
    coverage: 'full',
    g: { water: 78.18, protein: 19.44, fat: 0.98, carb: 0, fiber: 0, ash: 1.41 },
    mg: { sodium: 86, potassium: 356, calcium: 60, magnesium: 67, phosphorus: 221, iron: 0.46, zinc: 0.47, copper: 0.05, manganese: 0.015, vitaminE: 0.23, vitaminB1: 0.047, vitaminB2: 0.185, vitaminB3: 3.27, vitaminB5: 0.358, vitaminB6: 0.287 },
    ug: { selenium: 36.5, vitaminA: 14, vitaminD: 1, vitaminK: 0.1, vitaminB9: 3, vitaminB12: 3.19 },
  },
  {
    id: 'haddock',
    name: 'Haddock',
    category: 'aquatic',
    tags: ['fish', 'gadoid', 'lean'],
    source: 'USDA SR Legacy 171964 (Fish, haddock, raw)',
    confidence: 'high',
    coverage: 'full',
    g: { water: 83.38, protein: 16.32, fat: 0.45, carb: 0, fiber: 0, ash: 1.28 },
    mg: { sodium: 213, potassium: 286, calcium: 11, magnesium: 21, phosphorus: 227, iron: 0.17, zinc: 0.32, copper: 0.021, manganese: 0.011, vitaminB1: 0.02, vitaminB2: 0.057, vitaminB3: 3.363, vitaminB5: 0.403, vitaminB6: 0.281 },
    ug: { selenium: 25.9, vitaminB9: 12, vitaminB12: 1.83 },
  },
  {
    id: 'hake',
    name: 'Hake',
    category: 'aquatic',
    tags: ['fish', 'gadoid', 'lean'],
    source: 'Modelled from USDA SR Legacy 171955 Atlantic cod and 173713 whiting; published Merluccius macros',
    confidence: 'low',
    coverage: 'macroOnly',
    g: { water: 80.5, protein: 17, fat: 1.3, carb: 0, fiber: 0, ash: 1.3 },
  },
  {
    id: 'mullet',
    name: 'Mullet',
    category: 'aquatic',
    tags: ['fish', 'estuarine'],
    source: 'USDA SR Legacy 175123 (Fish, mullet, striped, raw)',
    confidence: 'high',
    coverage: 'full',
    g: { water: 77.01, protein: 19.35, fat: 3.79, carb: 0, fiber: 0, ash: 1.2 },
    mg: { sodium: 65, potassium: 357, calcium: 41, magnesium: 29, phosphorus: 221, iron: 1.02, zinc: 0.52, copper: 0.051, manganese: 0.016, vitaminE: 1, vitaminB1: 0.09, vitaminB2: 0.08, vitaminB3: 5.2, vitaminB5: 0.76, vitaminB6: 0.425, vitaminC: 1.2 },
    ug: { selenium: 36.5, vitaminA: 37, vitaminD: 1.5, vitaminK: 0.1, vitaminB9: 9, vitaminB12: 0.22 },
  },
  {
    id: 'sea_bass',
    name: 'Sea bass',
    category: 'aquatic',
    tags: ['fish', 'estuarine', 'predator'],
    source: 'USDA SR Legacy 175142 (Fish, sea bass, mixed species, raw)',
    confidence: 'high',
    coverage: 'full',
    g: { water: 78.27, protein: 18.43, fat: 2, carb: 0, fiber: 0, ash: 1.09 },
    mg: { sodium: 68, potassium: 256, calcium: 10, magnesium: 41, phosphorus: 194, iron: 0.29, zinc: 0.4, copper: 0.019, manganese: 0.015, vitaminE: 0.84, vitaminB1: 0.11, vitaminB2: 0.12, vitaminB3: 1.6, vitaminB5: 0.75, vitaminB6: 0.4 },
    ug: { selenium: 36.5, vitaminA: 46, vitaminD: 5.6, vitaminK: 0.1, vitaminB9: 5, vitaminB12: 0.3 },
  },
  {
    id: 'eel',
    name: 'Eel',
    category: 'aquatic',
    tags: ['fish', 'catadromous', 'oily'],
    source: 'USDA SR Legacy 174193 (Fish, eel, mixed species, raw)',
    confidence: 'high',
    coverage: 'full',
    g: { water: 68.26, protein: 18.44, fat: 11.66, carb: 0, fiber: 0, ash: 1.41 },
    mg: { sodium: 51, potassium: 272, calcium: 20, magnesium: 20, phosphorus: 216, iron: 0.5, zinc: 1.62, copper: 0.023, manganese: 0.035, vitaminE: 4, vitaminB1: 0.15, vitaminB2: 0.04, vitaminB3: 3.5, vitaminB5: 0.24, vitaminB6: 0.067, vitaminC: 1.8 },
    ug: { selenium: 6.5, vitaminA: 1043, vitaminD: 23.3, vitaminB9: 15, vitaminB12: 3 },
  },
  {
    id: 'samphire',
    name: 'Samphire',
    category: 'vegetable',
    tags: ['halophyte', 'saltmarsh', 'high-sodium'],
    source: 'Composite: nutritiontable.com fresh samphire minerals with carb/ash rebalanced to Salicornia literature (ash 2.5-4 g)',
    confidence: 'low',
    coverage: 'partial',
    g: { water: 87, protein: 3.1, fat: 0.7, carb: 5, fiber: 1.5, ash: 2.8 },
    mg: { sodium: 870, potassium: 50, calcium: 150, magnesium: 110, phosphorus: 80, iron: 2.2, zinc: 0.4, copper: 0.3, vitaminC: 3 },
  },
  {
    id: 'saltmarsh_grass',
    name: 'Saltmarsh grass',
    category: 'forage',
    tags: ['halophyte', 'saltmarsh', 'forage'],
    source: 'Modelled from Spartina/Puccinellia forage analyses (high fibre, salt-laden ash)',
    confidence: 'model',
    coverage: 'macroOnly',
    g: { water: 68, protein: 3, fat: 0.8, carb: 10, fiber: 14, ash: 4.5 },
  },
  {
    id: 'brackish_diatom_mat',
    name: 'Brackish diatom mat',
    category: 'algae',
    tags: ['microalgae', 'biofilm', 'siliceous'],
    source: 'Modelled from benthic diatom biofilm literature (siliceous frustule ash)',
    confidence: 'model',
    coverage: 'macroOnly',
    g: { water: 86, protein: 4, fat: 1.5, carb: 3, fiber: 0.5, ash: 5 },
  },
  {
    id: 'perch',
    name: 'Perch',
    category: 'aquatic',
    tags: ['fish', 'freshwater', 'lean'],
    source: 'USDA SR Legacy 173678 (Fish, perch, mixed species, raw)',
    confidence: 'high',
    coverage: 'full',
    g: { water: 79.13, protein: 19.39, fat: 0.92, carb: 0, fiber: 0, ash: 1.24 },
    mg: { sodium: 62, potassium: 269, calcium: 80, magnesium: 30, phosphorus: 200, iron: 0.9, zinc: 1.11, copper: 0.15, manganese: 0.7, vitaminE: 0.2, vitaminB1: 0.07, vitaminB2: 0.1, vitaminB3: 1.52, vitaminB5: 0.75, vitaminB6: 0.12, vitaminC: 1.7 },
    ug: { selenium: 12.6, vitaminA: 9, vitaminD: 3, vitaminK: 0.1, vitaminB9: 5, vitaminB12: 1.9 },
  },
  {
    id: 'pike',
    name: 'Pike',
    category: 'aquatic',
    tags: ['fish', 'freshwater', 'predator'],
    source: 'USDA SR Legacy 173680 (Fish, pike, northern, raw)',
    confidence: 'high',
    coverage: 'full',
    g: { water: 78.92, protein: 19.26, fat: 0.69, carb: 0, fiber: 0, ash: 1.2 },
    mg: { sodium: 39, potassium: 259, calcium: 57, magnesium: 31, phosphorus: 220, iron: 0.55, zinc: 0.67, copper: 0.051, manganese: 0.24, vitaminB1: 0.058, vitaminB2: 0.063, vitaminB3: 2.3, vitaminB5: 0.75, vitaminB6: 0.117, vitaminC: 3.8 },
    ug: { selenium: 12.6, vitaminB9: 15, vitaminB12: 2 },
  },
  {
    id: 'carp',
    name: 'Carp',
    category: 'aquatic',
    tags: ['fish', 'freshwater', 'oily'],
    source: 'USDA SR Legacy 171952 (Fish, carp, raw)',
    confidence: 'high',
    coverage: 'full',
    g: { water: 76.31, protein: 17.83, fat: 5.6, carb: 0, fiber: 0, ash: 1.46 },
    mg: { sodium: 49, potassium: 333, calcium: 41, magnesium: 29, phosphorus: 415, iron: 1.24, zinc: 1.48, copper: 0.057, manganese: 0.042, vitaminE: 0.63, vitaminB1: 0.115, vitaminB2: 0.055, vitaminB3: 1.64, vitaminB5: 0.75, vitaminB6: 0.19, vitaminC: 1.6 },
    ug: { selenium: 12.6, vitaminA: 9, vitaminD: 24.7, vitaminK: 0.1, vitaminB9: 15, vitaminB12: 1.53 },
  },
  {
    id: 'tilapia',
    name: 'Tilapia',
    category: 'aquatic',
    tags: ['fish', 'freshwater', 'lean'],
    source: 'USDA SR Legacy 175176 (Fish, tilapia, raw)',
    confidence: 'high',
    coverage: 'full',
    g: { water: 78.08, protein: 20.08, fat: 1.7, carb: 0, fiber: 0, ash: 0.93 },
    mg: { sodium: 52, potassium: 302, calcium: 10, magnesium: 27, phosphorus: 170, iron: 0.56, zinc: 0.33, copper: 0.075, manganese: 0.037, vitaminE: 0.4, vitaminB1: 0.041, vitaminB2: 0.063, vitaminB3: 3.903, vitaminB5: 0.487, vitaminB6: 0.162 },
    ug: { selenium: 41.8, vitaminD: 3.1, vitaminK: 1.4, vitaminB9: 24, vitaminB12: 1.58 },
  },
  {
    id: 'catfish',
    name: 'Catfish',
    category: 'aquatic',
    tags: ['fish', 'freshwater', 'benthic'],
    source: 'USDA SR Legacy 174186 (Fish, catfish, channel, wild, raw)',
    confidence: 'high',
    coverage: 'full',
    g: { water: 80.36, protein: 16.38, fat: 2.82, carb: 0, fiber: 0, ash: 0.96 },
    mg: { sodium: 43, potassium: 358, calcium: 14, magnesium: 23, phosphorus: 209, iron: 0.3, zinc: 0.51, copper: 0.034, manganese: 0.025, vitaminB1: 0.21, vitaminB2: 0.072, vitaminB3: 1.907, vitaminB5: 0.765, vitaminB6: 0.116, vitaminC: 0.7 },
    ug: { selenium: 12.6, vitaminA: 15, vitaminD: 12.5, vitaminB9: 10, vitaminB12: 2.23 },
  },
  {
    id: 'zander',
    name: 'Zander',
    category: 'aquatic',
    tags: ['fish', 'freshwater', 'predator'],
    source: 'Inferred from USDA SR Legacy 173680 northern pike and 173678 perch (Sander lucioperca is a percid)',
    confidence: 'low',
    coverage: 'macroOnly',
    g: { water: 79, protein: 19.3, fat: 0.7, carb: 0, fiber: 0, ash: 1.2 },
  },
  {
    id: 'bream',
    name: 'Bream',
    category: 'aquatic',
    tags: ['fish', 'freshwater', 'cyprinid'],
    source: 'Modelled from USDA SR Legacy 171952 carp (cyprinid relative), leaner published Abramis brama',
    confidence: 'model',
    coverage: 'macroOnly',
    g: { water: 76.5, protein: 17.5, fat: 4.5, carb: 0, fiber: 0, ash: 1.3 },
  },
  {
    id: 'roach',
    name: 'Roach',
    category: 'aquatic',
    tags: ['fish', 'freshwater', 'cyprinid'],
    source: 'Modelled from USDA SR Legacy 171952 carp (cyprinid relative); published Rutilus rutilus',
    confidence: 'model',
    coverage: 'macroOnly',
    g: { water: 78, protein: 17.8, fat: 2.8, carb: 0, fiber: 0, ash: 1.3 },
  },
  {
    id: 'freshwater_mussel',
    name: 'Freshwater mussel',
    category: 'aquatic',
    tags: ['mollusc', 'bivalve', 'freshwater'],
    source: 'USDA SR Legacy 174216 blue mussel as unionid proxy',
    confidence: 'low',
    coverage: 'full',
    g: { water: 80.58, protein: 11.9, fat: 2.24, carb: 3.69, fiber: 0, ash: 1.59 },
    mg: { sodium: 286, potassium: 320, calcium: 26, magnesium: 34, phosphorus: 197, iron: 3.95, zinc: 1.6, copper: 0.094, manganese: 3.4, vitaminE: 0.55, vitaminB1: 0.16, vitaminB2: 0.21, vitaminB3: 1.6, vitaminB5: 0.5, vitaminB6: 0.05, vitaminC: 8 },
    ug: { selenium: 44.8, vitaminA: 48, vitaminK: 0.1, vitaminB9: 42, vitaminB12: 12 },
  },
  {
    id: 'crayfish',
    name: 'Crayfish',
    category: 'aquatic',
    tags: ['crustacean', 'freshwater'],
    source: 'USDA SR Legacy 174206 (Crustaceans, crayfish, mixed species, wild, raw)',
    confidence: 'high',
    coverage: 'full',
    g: { water: 82.24, protein: 15.97, fat: 0.95, carb: 0, fiber: 0, ash: 1.34 },
    mg: { sodium: 58, potassium: 302, calcium: 27, magnesium: 27, phosphorus: 256, iron: 0.84, zinc: 1.3, copper: 0.419, manganese: 0.226, vitaminE: 2.85, vitaminB1: 0.07, vitaminB2: 0.032, vitaminB3: 2.208, vitaminB5: 0.546, vitaminB6: 0.108, vitaminC: 1.2 },
    ug: { selenium: 31.6, vitaminA: 16, vitaminK: 0.1, vitaminB9: 37, vitaminB12: 2 },
  },
  {
    id: 'lamprey',
    name: 'Lamprey',
    category: 'aquatic',
    tags: ['fish', 'anadromous', 'oily'],
    source: 'Modelled from published Petromyzon marinus (very high fat, 10-15 g)',
    confidence: 'model',
    coverage: 'macroOnly',
    g: { water: 69, protein: 17, fat: 12.5, carb: 0, fiber: 0, ash: 1.3 },
  },
  {
    id: 'char',
    name: 'Arctic char',
    category: 'aquatic',
    tags: ['fish', 'salmonid', 'cold-water'],
    source: 'Inferred from USDA SR Legacy 175154 wild rainbow trout (salmonid relative); fat raised to published Salvelinus alpinus',
    confidence: 'low',
    coverage: 'partial',
    g: { water: 72.5, protein: 20, fat: 5.5, carb: 0, fiber: 0, ash: 1.3 },
    mg: { sodium: 31, potassium: 481, calcium: 67, magnesium: 31, phosphorus: 271, iron: 0.7, zinc: 1.08, copper: 0.109, manganese: 0.158, vitaminB1: 0.123, vitaminB2: 0.105, vitaminB3: 5.384, vitaminB5: 0.928, vitaminB6: 0.406 },
    ug: { selenium: 12.6, vitaminB9: 12, vitaminB12: 4.45 },
  },
  {
    id: 'whitefish',
    name: 'Whitefish',
    category: 'aquatic',
    tags: ['fish', 'freshwater', 'oily'],
    source: 'USDA SR Legacy 173711 (Fish, whitefish, mixed species, raw)',
    confidence: 'high',
    coverage: 'full',
    g: { water: 72.77, protein: 19.09, fat: 5.86, carb: 0, fiber: 0, ash: 1.12 },
    mg: { sodium: 51, potassium: 317, calcium: 26, magnesium: 33, phosphorus: 270, iron: 0.37, zinc: 0.99, copper: 0.072, manganese: 0.067, vitaminE: 0.2, vitaminB1: 0.14, vitaminB2: 0.12, vitaminB3: 3, vitaminB5: 0.75, vitaminB6: 0.3 },
    ug: { selenium: 12.6, vitaminA: 36, vitaminD: 12, vitaminK: 0.1, vitaminB9: 15, vitaminB12: 1 },
  },
  {
    id: 'water_lily_root',
    name: 'Water lily root',
    category: 'vegetable',
    tags: ['rhizome', 'wetland', 'starchy'],
    source: 'Modelled from USDA SR Legacy 169250 lotus root (Nymphaeaceae relative)',
    confidence: 'low',
    coverage: 'macroOnly',
    g: { water: 79, protein: 2.4, fat: 0.2, carb: 12.5, fiber: 4.5, ash: 1 },
  },
  {
    id: 'reed_rhizome',
    name: 'Reed rhizome',
    category: 'vegetable',
    tags: ['rhizome', 'wetland', 'starchy'],
    source: 'Modelled from Phragmites australis rhizome analyses (starch-rich, fibrous)',
    confidence: 'model',
    coverage: 'macroOnly',
    g: { water: 72, protein: 2, fat: 0.4, carb: 18, fiber: 6, ash: 1.3 },
  },
  {
    id: 'duckweed',
    name: 'Duckweed',
    category: 'algae',
    tags: ['aquatic-plant', 'high-protein-dry'],
    source: 'Modelled from Lemna literature (90-95% water fresh; 35-45% protein dry)',
    confidence: 'low',
    coverage: 'macroOnly',
    g: { water: 92, protein: 2.5, fat: 0.4, carb: 1.8, fiber: 1.5, ash: 1.8 },
  },
  {
    id: 'freshwater_snail',
    name: 'Freshwater snail',
    category: 'aquatic',
    tags: ['mollusc', 'gastropod', 'freshwater'],
    source: 'USDA SR Legacy 167744 (Mollusks, snail, raw) as proxy',
    confidence: 'low',
    coverage: 'full',
    g: { water: 79.2, protein: 16.1, fat: 1.4, carb: 2, fiber: 0, ash: 1.3 },
    mg: { sodium: 70, potassium: 382, calcium: 10, magnesium: 250, phosphorus: 272, iron: 3.5, zinc: 1, copper: 0.4, vitaminE: 5, vitaminB1: 0.01, vitaminB2: 0.12, vitaminB3: 1.4, vitaminB6: 0.13 },
    ug: { selenium: 27.4, vitaminA: 30, vitaminK: 0.1, vitaminB9: 6, vitaminB12: 0.5 },
  },
  {
    id: 'arctic_cod',
    name: 'Arctic cod',
    category: 'aquatic',
    tags: ['fish', 'polar', 'gadoid'],
    source: 'Inferred from USDA SR Legacy 171955 Atlantic cod; lipid raised to published Boreogadus saida whole fish',
    confidence: 'low',
    coverage: 'partial',
    g: { water: 79.5, protein: 16.5, fat: 2.5, carb: 0, fiber: 0, ash: 1.5 },
    mg: { sodium: 54, potassium: 413, calcium: 16, magnesium: 32, phosphorus: 203, iron: 0.38, zinc: 0.45, vitaminB3: 2.063, vitaminB6: 0.245 },
    ug: { selenium: 33.1, vitaminB12: 0.91 },
  },
  {
    id: 'seal_blubber',
    name: 'Seal blubber',
    category: 'fat',
    tags: ['blubber', 'marine-mammal'],
    source: 'Modelled from USDA SR Legacy 167611 bearded seal oil and 167623 bowhead blubber (intact blubber tissue)',
    confidence: 'low',
    coverage: 'partial',
    g: { water: 6, protein: 2, fat: 91.5, carb: 0, fiber: 0, ash: 0.3 },
    mg: { vitaminE: 10.28 },
    ug: { vitaminA: 10, vitaminD: 0.7 },
  },
  {
    id: 'seal_meat',
    name: 'Seal meat',
    category: 'meat',
    tags: ['marine-mammal', 'iron-rich', 'polar'],
    source: 'USDA SR Legacy 168025 (Seal, ringed, meat, Alaska Native)',
    confidence: 'high',
    coverage: 'partial',
    g: { water: 67.4, protein: 28.4, fat: 3.2, carb: 0, fiber: 0, ash: 1 },
    mg: { sodium: 110, calcium: 5, phosphorus: 238, iron: 19.6, vitaminB1: 0.14, vitaminB2: 0.53, vitaminB5: 0.65 },
    ug: { vitaminA: 116 },
  },
  {
    id: 'walrus_meat',
    name: 'Walrus meat',
    category: 'meat',
    tags: ['marine-mammal', 'iron-rich', 'polar'],
    source: 'USDA SR Legacy 168029 (Walrus, meat, raw, Alaska Native)',
    confidence: 'high',
    coverage: 'partial',
    g: { water: 65.1, protein: 19.2, fat: 13.6, carb: 0, fiber: 0, ash: 2.1 },
    mg: { calcium: 18, phosphorus: 122, iron: 9.4, vitaminB1: 0.18, vitaminB2: 0.24, vitaminB3: 4.8 },
  },
  {
    id: 'muktuk',
    name: 'Muktuk (whale skin and blubber)',
    category: 'meat',
    tags: ['marine-mammal', 'blubber', 'polar'],
    source: 'USDA SR Legacy 167624 (Whale, bowhead, skin and subcutaneous fat/muktuk, Alaska Native)',
    confidence: 'high',
    coverage: 'partial',
    g: { water: 40, protein: 12.6, fat: 46.1, carb: 0, fiber: 0, ash: 0.1 },
    mg: { calcium: 5, vitaminB1: 0.08, vitaminB2: 0.02, vitaminB3: 0.8 },
  },
  {
    id: 'ice_algae',
    name: 'Ice algae',
    category: 'algae',
    tags: ['microalgae', 'polar', 'sea-ice'],
    source: 'Modelled from sea-ice diatom assemblage literature (siliceous ash, moderate protein)',
    confidence: 'model',
    coverage: 'macroOnly',
    g: { water: 88, protein: 3.5, fat: 1.2, carb: 2.5, fiber: 0.8, ash: 4 },
  },
  {
    id: 'polar_bear_liver',
    name: 'Polar bear liver',
    category: 'organ',
    tags: ['organ', 'toxic', 'vitamin-a-toxic', 'polar'],
    source: 'Vitamin A from Rodahl & Moore 1943 (13,000-18,000 IU/g wet; mean ~16,000 IU/g = ~480,000 ug retinol/100 g); macros modelled from USDA SR Legacy 168983 caribou liver',
    confidence: 'medium',
    coverage: 'partial',
    g: { water: 70, protein: 19, fat: 4.5, carb: 3.5, fiber: 0, ash: 2 },
    mg: { iron: 15.7 },
    ug: { vitaminA: 480000 },
  },
  {
    id: 'reindeer_caribou',
    name: 'Reindeer / caribou meat',
    category: 'meat',
    tags: ['game', 'tundra', 'lean'],
    source: 'USDA SR Legacy 168050 (Caribou, hind quarter meat, raw, Alaska Native)',
    confidence: 'high',
    coverage: 'full',
    g: { water: 72.6, protein: 22.63, fat: 3.37, carb: 0, fiber: 0, ash: 1.23 },
    mg: { sodium: 52, potassium: 320, calcium: 5, magnesium: 26, phosphorus: 230, iron: 4.1, zinc: 2.1, copper: 0.27, manganese: 0.037, vitaminE: 0.69, vitaminB1: 0.442, vitaminB2: 0.962, vitaminB3: 7.15, vitaminB5: 2.09, vitaminB6: 0.351 },
    ug: { selenium: 12.5, vitaminA: 94, vitaminK: 1.4, vitaminB9: 4, vitaminB12: 7.05 },
  },
  {
    id: 'muskox',
    name: 'Muskox meat',
    category: 'meat',
    tags: ['game', 'tundra', 'lean'],
    source: 'Modelled from USDA SR Legacy 168050 caribou and 174344 moose; published muskox protein 22-23 g, fat 1.5-2.5 g',
    confidence: 'low',
    coverage: 'macroOnly',
    g: { water: 74.5, protein: 22.5, fat: 1.8, carb: 0, fiber: 0, ash: 1.2 },
  },
  {
    id: 'ptarmigan',
    name: 'Ptarmigan',
    category: 'meat',
    tags: ['game-bird', 'tundra', 'lean'],
    source: 'USDA SR Legacy 172831 ruffed grouse breast as tetraonid proxy for Lagopus',
    confidence: 'low',
    coverage: 'full',
    g: { water: 72.93, protein: 25.94, fat: 0.88, carb: 0, fiber: 0, ash: 1.07 },
    mg: { sodium: 50, potassium: 311, calcium: 5, magnesium: 32, phosphorus: 229, iron: 0.58, zinc: 0.51, copper: 0.058, manganese: 0.016, vitaminE: 0.73, vitaminB1: 0.042, vitaminB2: 0.28, vitaminB3: 11.6, vitaminB6: 1.275 },
    ug: { vitaminA: 5, vitaminB12: 2.9 },
  },
  {
    id: 'arctic_hare',
    name: 'Arctic hare',
    category: 'meat',
    tags: ['game', 'tundra', 'lean'],
    source: 'USDA SR Legacy 174347 (Game meat, rabbit, wild, raw) as Lepus proxy',
    confidence: 'low',
    coverage: 'partial',
    g: { water: 74.51, protein: 21.79, fat: 2.32, carb: 0, fiber: 0, ash: 1.12 },
    mg: { sodium: 50, potassium: 378, calcium: 12, magnesium: 29, phosphorus: 226, iron: 3.2, vitaminB1: 0.03, vitaminB2: 0.06, vitaminB3: 6.5 },
    ug: { selenium: 9.4 },
  },
  {
    id: 'moose',
    name: 'Moose meat',
    category: 'meat',
    tags: ['game', 'taiga', 'lean'],
    source: 'USDA SR Legacy 174344 (Game meat, moose, raw)',
    confidence: 'high',
    coverage: 'full',
    g: { water: 75.55, protein: 22.24, fat: 0.74, carb: 0, fiber: 0, ash: 1.13 },
    mg: { sodium: 65, potassium: 317, calcium: 5, magnesium: 23, phosphorus: 158, iron: 3.21, zinc: 2.8, copper: 0.067, manganese: 0.008, vitaminB1: 0.06, vitaminB2: 0.27, vitaminB3: 5, vitaminC: 4 },
    ug: { selenium: 9.6 },
  },
  {
    id: 'elk',
    name: 'Elk meat',
    category: 'meat',
    tags: ['game', 'taiga', 'lean'],
    source: 'USDA SR Legacy 175301 (Game meat, elk, raw)',
    confidence: 'high',
    coverage: 'full',
    g: { water: 74.38, protein: 22.95, fat: 1.45, carb: 0, fiber: 0, ash: 1 },
    mg: { sodium: 58, potassium: 312, calcium: 4, magnesium: 23, phosphorus: 161, iron: 2.76, zinc: 2.4, copper: 0.12, manganese: 0.012 },
    ug: { selenium: 9.8 },
  },
  {
    id: 'bear_meat',
    name: 'Bear meat',
    category: 'meat',
    tags: ['game', 'taiga', 'fatty'],
    source: 'USDA SR Legacy 173845 (Game meat, bear, raw)',
    confidence: 'high',
    coverage: 'partial',
    g: { water: 71.2, protein: 20.1, fat: 8.3, carb: 0, fiber: 0, ash: 0.7 },
    mg: { calcium: 3, phosphorus: 151, iron: 6.65, vitaminB1: 0.16, vitaminB2: 0.68, vitaminB3: 3.2 },
    ug: { selenium: 8.3 },
  },
  {
    id: 'beaver',
    name: 'Beaver meat',
    category: 'meat',
    tags: ['game', 'taiga', 'aquatic-mammal'],
    source: 'USDA SR Legacy 175294 (Game meat, beaver, raw)',
    confidence: 'high',
    coverage: 'partial',
    g: { water: 70.97, protein: 24.05, fat: 4.8, carb: 0, fiber: 0, ash: 1 },
    mg: { sodium: 51, potassium: 348, calcium: 15, magnesium: 25, phosphorus: 237, iron: 6.9, vitaminB1: 0.06, vitaminB2: 0.22, vitaminB3: 1.9, vitaminC: 2 },
    ug: { selenium: 26.6 },
  },
  {
    id: 'lichen',
    name: 'Lichen (reindeer moss)',
    category: 'forage',
    tags: ['lichen', 'tundra', 'forage', 'lichenin'],
    source: 'Modelled from terricolous Cladonia nutritive-value literature (Lichenologist 2002): crude protein 1.5-3%, ash 1-3%, lichenin-dominated carbohydrate',
    confidence: 'low',
    coverage: 'macroOnly',
    g: { water: 12, protein: 2.2, fat: 2, carb: 66, fiber: 15, ash: 2.5 },
  },
  {
    id: 'cloudberry',
    name: 'Cloudberry',
    category: 'fruit',
    tags: ['berry', 'tundra', 'vitamin-c'],
    source: 'USDA SR Legacy 169802 (Cloudberries, raw, Alaska Native); total carb split into net carb and published fibre',
    confidence: 'medium',
    coverage: 'partial',
    g: { water: 87, protein: 2.4, fat: 0.8, carb: 2.6, fiber: 6, ash: 1.2 },
    mg: { calcium: 18, phosphorus: 35, iron: 0.7, vitaminB1: 0.05, vitaminB2: 0.07, vitaminB3: 0.9, vitaminC: 158 },
  },
  {
    id: 'lingonberry',
    name: 'Lingonberry',
    category: 'fruit',
    tags: ['berry', 'tundra'],
    source: 'Finnish/Nordic food-table values for Vaccinium vitis-idaea',
    confidence: 'low',
    coverage: 'partial',
    g: { water: 87.4, protein: 0.4, fat: 0.6, carb: 6.3, fiber: 3, ash: 0.3 },
    mg: { vitaminC: 10 },
  },
  {
    id: 'crowberry',
    name: 'Crowberry',
    category: 'fruit',
    tags: ['berry', 'tundra'],
    source: 'Modelled from Empetrum nigrum literature and USDA wild-blueberry row',
    confidence: 'model',
    coverage: 'partial',
    g: { water: 84, protein: 0.5, fat: 1, carb: 9, fiber: 4, ash: 0.4 },
    mg: { vitaminC: 25 },
  },
  {
    id: 'bilberry',
    name: 'Bilberry',
    category: 'fruit',
    tags: ['berry', 'tundra', 'anthocyanin'],
    source: 'USDA SR Legacy 167640 (Blueberries, wild, raw, Alaska Native); carb restated net of fibre',
    confidence: 'high',
    coverage: 'full',
    g: { water: 85.48, protein: 1.22, fat: 0.76, carb: 9.71, fiber: 2.6, ash: 0.23 },
    mg: { sodium: 6, potassium: 75, calcium: 13, magnesium: 7, phosphorus: 29, iron: 0.37, zinc: 0.2, copper: 0.03, manganese: 2, vitaminE: 1.69, vitaminB1: 0.067, vitaminB2: 0.414, vitaminB3: 0.597, vitaminB5: 0.265, vitaminB6: 0.026, vitaminC: 18.3 },
    ug: { vitaminA: 6, vitaminK: 17.2, vitaminB9: 33 },
  },
  {
    id: 'rosehip',
    name: 'Rosehip',
    category: 'fruit',
    tags: ['fruit', 'vitamin-c', 'high-fibre'],
    source: 'USDA SR Legacy 168998 (Rose Hips, wild, Northern Plains Indians); carb restated net of fibre',
    confidence: 'high',
    coverage: 'full',
    g: { water: 58.66, protein: 1.6, fat: 0.34, carb: 14.12, fiber: 24.1, ash: 1.18 },
    mg: { sodium: 4, potassium: 429, calcium: 169, magnesium: 69, phosphorus: 61, iron: 1.06, zinc: 0.25, copper: 0.113, manganese: 1.02, vitaminE: 5.84, vitaminB1: 0.016, vitaminB2: 0.166, vitaminB3: 1.3, vitaminB5: 0.8, vitaminB6: 0.076, vitaminC: 426 },
    ug: { vitaminA: 217, vitaminK: 25.9, vitaminB9: 3 },
  },
  {
    id: 'pine_nut',
    name: 'Pine nut',
    category: 'nut',
    tags: ['nut', 'taiga', 'oily'],
    source: 'USDA SR Legacy 170591 (Nuts, pine nuts, dried); carb restated net of fibre',
    confidence: 'high',
    coverage: 'full',
    g: { water: 2.28, protein: 13.69, fat: 68.37, carb: 9.38, fiber: 3.7, ash: 2.59 },
    mg: { sodium: 2, potassium: 597, calcium: 16, magnesium: 251, phosphorus: 575, iron: 5.53, zinc: 6.45, copper: 1.324, manganese: 8.802, vitaminE: 9.33, vitaminB1: 0.364, vitaminB2: 0.227, vitaminB3: 4.387, vitaminB5: 0.313, vitaminB6: 0.094, vitaminC: 0.8 },
    ug: { selenium: 0.7, vitaminA: 1, vitaminK: 53.9, vitaminB9: 34 },
  },
  {
    id: 'birch_sap',
    name: 'Birch sap',
    category: 'fluid',
    tags: ['sap', 'taiga', 'dilute'],
    source: 'Published silver/downy birch sap composition (Forests 2020, 11:365; Wikipedia summary table)',
    confidence: 'medium',
    coverage: 'partial',
    g: { water: 98.6, protein: 0, fat: 0, carb: 1.1, fiber: 0, ash: 0.25 },
    mg: { potassium: 120, calcium: 60, magnesium: 11, phosphorus: 6.4, manganese: 1.1 },
  },
  {
    id: 'spruce_tip',
    name: 'Spruce tip',
    category: 'forage',
    tags: ['conifer', 'forage', 'vitamin-c'],
    source: 'Modelled from conifer shoot analyses; vitamin C from published spruce/pine tip range',
    confidence: 'low',
    coverage: 'partial',
    g: { water: 72, protein: 3.5, fat: 1.5, carb: 12, fiber: 9, ash: 1.8 },
    mg: { vitaminC: 200 },
  },
  {
    id: 'fiddlehead_fern',
    name: 'Fiddlehead fern',
    category: 'vegetable',
    tags: ['wild-green', 'spring'],
    source: 'USDA SR Legacy 169405 (Fiddlehead ferns, raw)',
    confidence: 'high',
    coverage: 'full',
    g: { water: 88.68, protein: 4.55, fat: 0.4, carb: 5.54, fiber: 0, ash: 0.83 },
    mg: { sodium: 1, potassium: 370, calcium: 32, magnesium: 34, phosphorus: 101, iron: 1.31, zinc: 0.83, copper: 0.32, manganese: 0.51, vitaminB1: 0.02, vitaminB2: 0.21, vitaminB3: 4.98, vitaminC: 26.6 },
    ug: { vitaminA: 181 },
  },
  {
    id: 'cattail_root',
    name: 'Cattail root',
    category: 'vegetable',
    tags: ['rhizome', 'wetland', 'starchy'],
    source: 'Modelled from Typha latifolia rhizome analyses (starch-rich, fibrous)',
    confidence: 'model',
    coverage: 'macroOnly',
    g: { water: 70, protein: 1.2, fat: 0.3, carb: 22, fiber: 5, ash: 1.3 },
  },
  {
    id: 'wild_garlic',
    name: 'Wild garlic',
    category: 'vegetable',
    tags: ['wild-green', 'allium'],
    source: 'Modelled from Allium ursinum literature; vitamin C from published range',
    confidence: 'low',
    coverage: 'partial',
    g: { water: 84, protein: 2.5, fat: 0.5, carb: 6.5, fiber: 5, ash: 1.2 },
    mg: { vitaminC: 150 },
  },
  {
    id: 'chaga',
    name: 'Chaga',
    category: 'fungus',
    tags: ['fungus', 'taiga', 'sclerotium', 'inedible-raw'],
    source: 'Modelled from Inonotus obliquus sclerotium analyses (low protein, high insoluble polysaccharide and ash)',
    confidence: 'model',
    coverage: 'macroOnly',
    g: { water: 10, protein: 2.5, fat: 1.5, carb: 50, fiber: 32, ash: 4 },
  },
  {
    id: 'morel',
    name: 'Morel',
    category: 'fungus',
    tags: ['fungus', 'wild-mushroom', 'iron-rich'],
    source: 'USDA SR Legacy 168423 (Mushrooms, morel, raw); carb restated net of fibre',
    confidence: 'high',
    coverage: 'full',
    g: { water: 89.61, protein: 3.12, fat: 0.57, carb: 2.3, fiber: 2.8, ash: 1.58 },
    mg: { sodium: 21, potassium: 411, calcium: 43, magnesium: 19, phosphorus: 194, iron: 12.18, zinc: 2.03, copper: 0.625, manganese: 0.587, vitaminB1: 0.069, vitaminB2: 0.205, vitaminB3: 2.252, vitaminB5: 0.44, vitaminB6: 0.136 },
    ug: { selenium: 2.2, vitaminD: 5.1, vitaminB9: 9 },
  },
  {
    id: 'chanterelle',
    name: 'Chanterelle',
    category: 'fungus',
    tags: ['fungus', 'wild-mushroom'],
    source: 'USDA SR Legacy 168422 (Mushrooms, Chanterelle, raw); carb restated net of fibre',
    confidence: 'high',
    coverage: 'full',
    g: { water: 89.85, protein: 1.49, fat: 0.53, carb: 3.06, fiber: 3.8, ash: 1.26 },
    mg: { sodium: 9, potassium: 506, calcium: 15, magnesium: 13, phosphorus: 57, iron: 3.47, zinc: 0.71, copper: 0.353, manganese: 0.286, vitaminB1: 0.015, vitaminB2: 0.215, vitaminB3: 4.085, vitaminB5: 1.075, vitaminB6: 0.044 },
    ug: { selenium: 2.2, vitaminD: 5.3, vitaminB9: 2 },
  },
  {
    id: 'porcini',
    name: 'Porcini',
    category: 'fungus',
    tags: ['fungus', 'wild-mushroom'],
    source: 'Modelled from fresh Boletus edulis literature (dried/rehydrated figures in Food Chem. studies back-calculated to fresh)',
    confidence: 'low',
    coverage: 'macroOnly',
    g: { water: 88, protein: 3.1, fat: 0.5, carb: 3.9, fiber: 2.5, ash: 1 },
  },
  {
    id: 'truffle',
    name: 'Truffle',
    category: 'fungus',
    tags: ['fungus', 'hypogeous'],
    source: 'Modelled from fresh Tuber melanosporum literature (high fibre, moderate protein)',
    confidence: 'low',
    coverage: 'macroOnly',
    g: { water: 73, protein: 6, fat: 0.5, carb: 7, fiber: 11, ash: 2 },
  },
  {
    id: 'camel_meat',
    name: 'Camel meat',
    category: 'meat',
    tags: ['game', 'desert', 'lean'],
    source: 'Nutritional values and health benefits of dromedary camel meat (PMC9374515), Tables 2, 5 and 6; mid-range values',
    confidence: 'medium',
    coverage: 'full',
    g: { water: 74, protein: 20.5, fat: 3.5, carb: 0, fiber: 0, ash: 0.95 },
    mg: { sodium: 150, potassium: 350, calcium: 10, magnesium: 25, phosphorus: 200, iron: 2.5, zinc: 4.5, copper: 0.1, vitaminE: 0.88, vitaminB1: 0.095, vitaminB2: 0.24, vitaminB5: 0.75, vitaminB6: 0.6 },
    ug: { vitaminA: 10.6, vitaminB12: 4.7 },
  },
  {
    id: 'camel_milk',
    name: 'Camel milk',
    category: 'egg',
    tags: ['dairy', 'desert', 'fluid'],
    source: 'FAO X6528E (Composition of camel milk), mid-range values',
    confidence: 'medium',
    coverage: 'partial',
    g: { water: 87, protein: 3.5, fat: 3.5, carb: 4.4, fiber: 0, ash: 0.79 },
    mg: { vitaminC: 7.5 },
  },
  {
    id: 'ostrich_meat',
    name: 'Ostrich meat',
    category: 'meat',
    tags: ['game-bird', 'savanna', 'lean'],
    source: 'USDA SR Legacy 174481 (Ostrich, ground, raw)',
    confidence: 'high',
    coverage: 'full',
    g: { water: 71.07, protein: 20.22, fat: 8.7, carb: 0, fiber: 0, ash: 0.73 },
    mg: { sodium: 72, potassium: 291, calcium: 7, magnesium: 20, phosphorus: 199, iron: 2.91, zinc: 3.51, copper: 0.128, manganese: 0.017, vitaminE: 0.24, vitaminB1: 0.182, vitaminB2: 0.267, vitaminB3: 4.377, vitaminB5: 1.08, vitaminB6: 0.475 },
    ug: { selenium: 33, vitaminB9: 7, vitaminB12: 4.61 },
  },
  {
    id: 'antelope',
    name: 'Antelope / gazelle',
    category: 'meat',
    tags: ['game', 'savanna', 'lean'],
    source: 'USDA SR Legacy 175292 (Game meat, antelope, raw)',
    confidence: 'high',
    coverage: 'full',
    g: { water: 74.08, protein: 22.38, fat: 2.03, carb: 0, fiber: 0, ash: 1.1 },
    mg: { sodium: 51, potassium: 353, calcium: 3, magnesium: 27, phosphorus: 188, iron: 3.19, zinc: 1.28, copper: 0.18, manganese: 0.02, vitaminB1: 0.32, vitaminB2: 0.58 },
    ug: { selenium: 9.7 },
  },
  {
    id: 'warthog',
    name: 'Warthog',
    category: 'meat',
    tags: ['game', 'savanna', 'suid'],
    source: 'Modelled from wild-boar and game-suid analyses (lean wild pig)',
    confidence: 'model',
    coverage: 'macroOnly',
    g: { water: 73.5, protein: 21.5, fat: 3.5, carb: 0, fiber: 0, ash: 1.1 },
  },
  {
    id: 'zebra',
    name: 'Zebra',
    category: 'meat',
    tags: ['game', 'savanna', 'equid'],
    source: 'Modelled from lean equid muscle analyses (horse/zebra)',
    confidence: 'model',
    coverage: 'macroOnly',
    g: { water: 73.5, protein: 21.5, fat: 2.8, carb: 0, fiber: 0, ash: 1.1 },
  },
  {
    id: 'mopane_worm',
    name: 'Mopane worm',
    category: 'insect',
    tags: ['insect', 'dried', 'savanna', 'iron-rich'],
    source: 'Compositional analyses of traditionally fire-treated and dried Mopane worms (AAUN 2018); mid-range values',
    confidence: 'medium',
    coverage: 'partial',
    g: { water: 10.2, protein: 58, fat: 11, carb: 8, fiber: 6, ash: 6.6 },
    mg: { sodium: 120, potassium: 1190, calcium: 360, magnesium: 390, iron: 17, zinc: 13.8 },
  },
  {
    id: 'witchetty_grub',
    name: 'Witchetty grub',
    category: 'insect',
    tags: ['insect', 'larva', 'arid', 'fatty'],
    source: 'Published Australian bush-food analyses of wood-moth larvae (very high fat)',
    confidence: 'low',
    coverage: 'macroOnly',
    g: { water: 60, protein: 15, fat: 19, carb: 1, fiber: 2, ash: 1.5 },
  },
  {
    id: 'prickly_pear',
    name: 'Prickly pear fruit',
    category: 'fruit',
    tags: ['cactus', 'fruit', 'arid'],
    source: 'USDA SR Legacy 167750 (Prickly pears, raw); carb restated net of fibre',
    confidence: 'high',
    coverage: 'full',
    g: { water: 87.55, protein: 0.73, fat: 0.51, carb: 5.97, fiber: 3.6, ash: 1.64 },
    mg: { sodium: 5, potassium: 220, calcium: 56, magnesium: 85, phosphorus: 24, iron: 0.3, zinc: 0.12, copper: 0.08, vitaminB1: 0.014, vitaminB2: 0.06, vitaminB3: 0.46, vitaminB6: 0.06, vitaminC: 14 },
    ug: { selenium: 0.6, vitaminA: 2, vitaminB9: 6 },
  },
  {
    id: 'nopal',
    name: 'Nopal (cactus pad)',
    category: 'vegetable',
    tags: ['cactus', 'arid', 'mucilage'],
    source: 'USDA SR Legacy 168571 (Nopales, raw); carb restated net of fibre',
    confidence: 'high',
    coverage: 'full',
    g: { water: 94.12, protein: 1.32, fat: 0.09, carb: 1.13, fiber: 2.2, ash: 1.14 },
    mg: { sodium: 21, potassium: 257, calcium: 164, magnesium: 52, phosphorus: 16, iron: 0.59, zinc: 0.25, copper: 0.052, manganese: 0.457, vitaminB1: 0.012, vitaminB2: 0.041, vitaminB3: 0.41, vitaminB5: 0.167, vitaminB6: 0.07, vitaminC: 9.3 },
    ug: { selenium: 0.7, vitaminB9: 3 },
  },
  {
    id: 'saguaro_fruit',
    name: 'Saguaro fruit',
    category: 'fruit',
    tags: ['cactus', 'fruit', 'arid'],
    source: 'Modelled from Sonoran cactus-fruit analyses (Carnegiea gigantea; seedy pulp)',
    confidence: 'model',
    coverage: 'macroOnly',
    g: { water: 80, protein: 1.8, fat: 1.2, carb: 11, fiber: 4.5, ash: 1.3 },
  },
  {
    id: 'wattleseed',
    name: 'Wattleseed (acacia seed)',
    category: 'legume',
    tags: ['seed', 'arid', 'roasted'],
    source: 'Modelled from Australian Acacia victoriae seed analyses (high protein and fibre)',
    confidence: 'low',
    coverage: 'macroOnly',
    g: { water: 7, protein: 20, fat: 8, carb: 30, fiber: 32, ash: 3 },
  },
  {
    id: 'baobab_fruit',
    name: 'Baobab fruit',
    category: 'fruit',
    tags: ['fruit', 'savanna', 'dried-pulp', 'vitamin-c'],
    source: 'USDA SR Legacy 167806 (Baobab powder); carb restated net of fibre',
    confidence: 'high',
    coverage: 'full',
    g: { water: 10.92, protein: 3.69, fat: 0.47, carb: 35.15, fiber: 44.5, ash: 5.28 },
    mg: { sodium: 10, potassium: 2189, calcium: 342, magnesium: 158, phosphorus: 47, iron: 8.42, zinc: 0.92, vitaminB1: 0.03, vitaminB2: 0.074, vitaminB3: 19.983, vitaminB6: 2.414, vitaminC: 173.2 },
    ug: { vitaminB9: 43 },
  },
  {
    id: 'marula_fruit',
    name: 'Marula fruit',
    category: 'fruit',
    tags: ['fruit', 'savanna', 'vitamin-c'],
    source: 'Modelled from Sclerocarya birrea pulp reviews (vitamin C 150-250 mg/100 g)',
    confidence: 'low',
    coverage: 'partial',
    g: { water: 85, protein: 0.6, fat: 0.2, carb: 11, fiber: 2, ash: 0.5 },
    mg: { vitaminC: 200 },
  },
  {
    id: 'tef',
    name: 'Tef',
    category: 'grain',
    tags: ['grain', 'highland', 'iron-rich'],
    source: 'USDA SR Legacy 169747 (Teff, uncooked); carb restated net of fibre',
    confidence: 'high',
    coverage: 'full',
    g: { water: 8.82, protein: 13.3, fat: 2.38, carb: 65.13, fiber: 8, ash: 2.37 },
    mg: { sodium: 12, potassium: 427, calcium: 180, magnesium: 184, phosphorus: 429, iron: 7.63, zinc: 3.63, copper: 0.81, manganese: 9.24, vitaminE: 0.08, vitaminB1: 0.39, vitaminB2: 0.27, vitaminB3: 3.363, vitaminB5: 0.942, vitaminB6: 0.482 },
    ug: { selenium: 4.4, vitaminK: 1.9 },
  },
  {
    id: 'sorghum',
    name: 'Sorghum',
    category: 'grain',
    tags: ['grain', 'savanna'],
    source: 'USDA SR Legacy 168943 (Sorghum flour, whole-grain); carb restated net of fibre',
    confidence: 'high',
    coverage: 'full',
    g: { water: 10.26, protein: 8.43, fat: 3.34, carb: 70.04, fiber: 6.6, ash: 1.32 },
    mg: { sodium: 3, potassium: 324, calcium: 12, magnesium: 123, phosphorus: 278, iron: 3.14, zinc: 1.63, copper: 0.253, manganese: 1.258, vitaminE: 0.5, vitaminB1: 0.329, vitaminB2: 0.061, vitaminB3: 4.496, vitaminB5: 0.539, vitaminB6: 0.325, vitaminC: 0.8 },
    ug: { selenium: 12.2, vitaminK: 6.4, vitaminB9: 25 },
  },
  {
    id: 'fonio',
    name: 'Fonio',
    category: 'grain',
    tags: ['grain', 'savanna'],
    source: 'Modelled from published Digitaria exilis grain analyses',
    confidence: 'low',
    coverage: 'macroOnly',
    g: { water: 10, protein: 7.5, fat: 2, carb: 72, fiber: 6.5, ash: 1.5 },
  },
  {
    id: 'desert_truffle',
    name: 'Desert truffle',
    category: 'fungus',
    tags: ['fungus', 'arid', 'hypogeous'],
    source: 'Modelled from Terfezia/Tirmania analyses (J. Food Biochem. 2026; Saudi truffle studies)',
    confidence: 'low',
    coverage: 'macroOnly',
    g: { water: 75, protein: 5, fat: 1, carb: 10, fiber: 6.5, ash: 2 },
  },
  {
    id: 'agave_sap',
    name: 'Agave sap',
    category: 'refined',
    tags: ['syrup', 'sugar', 'arid'],
    source: 'Published agave nectar composition (fructan-derived syrup)',
    confidence: 'low',
    coverage: 'partial',
    g: { water: 23, protein: 0.1, fat: 0.45, carb: 76, fiber: 0.2, ash: 0.25 },
    mg: { sodium: 4, potassium: 4, calcium: 1 },
  },
  {
    id: 'mesquite_pod_flour',
    name: 'Mesquite pod flour',
    category: 'legume',
    tags: ['legume', 'arid', 'high-fibre'],
    source: 'Modelled from Prosopis pod-flour analyses (high fibre, moderate protein)',
    confidence: 'low',
    coverage: 'macroOnly',
    g: { water: 8, protein: 11, fat: 2.5, carb: 48, fiber: 27, ash: 3.5 },
  },
  {
    id: 'jojoba_seed',
    name: 'Jojoba seed',
    category: 'nut',
    tags: ['seed', 'arid', 'wax-ester', 'indigestible'],
    source: 'Modelled from Simmondsia chinensis seed analyses (~50% liquid wax ester, simmondsin present)',
    confidence: 'model',
    coverage: 'macroOnly',
    g: { water: 5, protein: 15, fat: 50, carb: 14, fiber: 13, ash: 3 },
  },
  {
    id: 'argan_nut',
    name: 'Argan nut',
    category: 'nut',
    tags: ['nut', 'arid', 'oily'],
    source: 'Modelled from Argania spinosa kernel analyses (~50-55% oil)',
    confidence: 'low',
    coverage: 'macroOnly',
    g: { water: 4, protein: 14, fat: 55, carb: 15, fiber: 9, ash: 3 },
  },
  {
    id: 'chamois_ibex',
    name: 'Chamois / ibex meat',
    category: 'meat',
    tags: ['game', 'alpine', 'lean'],
    source: 'USDA SR Legacy 175303 (Game meat, goat, raw) as caprine proxy',
    confidence: 'low',
    coverage: 'partial',
    g: { water: 75.84, protein: 20.6, fat: 2.31, carb: 0, fiber: 0, ash: 1.11 },
    mg: { sodium: 82, potassium: 385, calcium: 13, phosphorus: 180, iron: 2.83, zinc: 4, copper: 0.256, manganese: 0.038, vitaminB1: 0.11, vitaminB2: 0.49, vitaminB3: 3.75 },
    ug: { selenium: 8.8, vitaminB9: 5, vitaminB12: 1.13 },
  },
  {
    id: 'marmot',
    name: 'Marmot',
    category: 'meat',
    tags: ['game', 'alpine', 'fatty'],
    source: 'Modelled from USDA SR Legacy 175294 beaver and 172523 squirrel (large sciurid, pre-hibernation fat)',
    confidence: 'model',
    coverage: 'macroOnly',
    g: { water: 70, protein: 21, fat: 7, carb: 0, fiber: 0, ash: 1.1 },
  },
  {
    id: 'yak_meat',
    name: 'Yak meat',
    category: 'meat',
    tags: ['game', 'alpine', 'lean'],
    source: 'Animal Frontiers 2023, 13:24 (yak protein 21.6%, fat 1%, K/Na/Fe/Zn); water and ash inferred from lean bovine',
    confidence: 'medium',
    coverage: 'partial',
    g: { water: 75.5, protein: 21.6, fat: 1, carb: 0, fiber: 0, ash: 1.1 },
    mg: { sodium: 80, potassium: 338, iron: 2.33, zinc: 3.34 },
  },
  {
    id: 'yak_butter',
    name: 'Yak butter',
    category: 'fat',
    tags: ['dairy-fat', 'alpine'],
    source: 'Modelled from USDA SR Legacy 173430 unsalted butter with higher yak-butter fat content',
    confidence: 'low',
    coverage: 'partial',
    g: { water: 14, protein: 0.9, fat: 83, carb: 0.1, fiber: 0, ash: 0.15 },
    mg: { sodium: 11, potassium: 24, calcium: 24, phosphorus: 24, vitaminE: 2.32 },
    ug: { vitaminA: 684, vitaminK: 7 },
  },
  {
    id: 'alpine_herb_pasture',
    name: 'Alpine herb pasture',
    category: 'forage',
    tags: ['forage', 'alpine', 'mixed-sward'],
    source: 'Modelled from alpine mixed-sward forage analyses',
    confidence: 'model',
    coverage: 'macroOnly',
    g: { water: 70, protein: 4, fat: 1, carb: 9, fiber: 14, ash: 2.2 },
  },
  {
    id: 'juniper_berry',
    name: 'Juniper berry',
    category: 'fruit',
    tags: ['berry', 'alpine', 'aromatic'],
    source: 'Modelled from Juniperus communis cone analyses (sugar-rich, resinous)',
    confidence: 'model',
    coverage: 'macroOnly',
    g: { water: 55, protein: 1, fat: 1.5, carb: 30, fiber: 11, ash: 1.3 },
  },
  {
    id: 'rowan_berry',
    name: 'Rowan berry',
    category: 'fruit',
    tags: ['berry', 'alpine', 'vitamin-c'],
    source: 'Matvaretabellen.no (Rowan-berries, raw); minerals and vitamin C converted from Nordic reference-intake percentages; ash inferred',
    confidence: 'medium',
    coverage: 'partial',
    g: { water: 86.4, protein: 0.7, fat: 0, carb: 6.3, fiber: 6, ash: 0.6 },
    mg: { potassium: 315, calcium: 32, magnesium: 25, phosphorus: 42, iron: 1, zinc: 0.18, vitaminC: 76 },
  },
  {
    id: 'capybara',
    name: 'Capybara',
    category: 'meat',
    tags: ['game', 'rainforest', 'rodent'],
    source: 'Modelled from PLOS ONE 2025 Amazonian wild-meat table (paca/agouti rows) plus capybara meat reviews',
    confidence: 'low',
    coverage: 'macroOnly',
    g: { water: 74, protein: 22, fat: 3, carb: 0, fiber: 0, ash: 1 },
  },
  {
    id: 'peccary',
    name: 'Peccary',
    category: 'meat',
    tags: ['game', 'rainforest', 'suid'],
    source: 'PLOS ONE 2025, Proximate composition of wild meats of the Brazilian Amazon, Table 4 (white-lipped peccary)',
    confidence: 'medium',
    coverage: 'macroOnly',
    g: { water: 76.06, protein: 22.23, fat: 1.81, carb: 0, fiber: 0, ash: 0.9 },
  },
  {
    id: 'tapir',
    name: 'Tapir',
    category: 'meat',
    tags: ['game', 'rainforest'],
    source: 'PLOS ONE 2025 Amazonian wild-meat table (lowland tapir: moisture 73.51, lipid 8.89, ash 1.09); protein rebalanced so macros sum',
    confidence: 'low',
    coverage: 'macroOnly',
    g: { water: 73.5, protein: 16.4, fat: 8.9, carb: 0, fiber: 0, ash: 1.1 },
  },
  {
    id: 'monkey_meat',
    name: 'Monkey meat',
    category: 'meat',
    tags: ['game', 'rainforest', 'primate'],
    source: 'PLOS ONE 2025 Amazonian wild-meat table (howler monkey, Alouatta juara)',
    confidence: 'medium',
    coverage: 'macroOnly',
    g: { water: 73.8, protein: 22.77, fat: 3.43, carb: 0, fiber: 0, ash: 0.99 },
  },
  {
    id: 'iguana',
    name: 'Iguana',
    category: 'meat',
    tags: ['reptile', 'rainforest', 'lean'],
    source: 'Modelled from published iguana/lizard muscle analyses (very lean, high protein)',
    confidence: 'low',
    coverage: 'macroOnly',
    g: { water: 73, protein: 24, fat: 1.5, carb: 0, fiber: 0, ash: 1.2 },
  },
  {
    id: 'caiman',
    name: 'Caiman',
    category: 'meat',
    tags: ['reptile', 'rainforest', 'crocodilian'],
    source: 'PLOS ONE 2025 Amazonian wild-meat table (spectacled caiman, Caiman crocodilus)',
    confidence: 'medium',
    coverage: 'macroOnly',
    g: { water: 75.96, protein: 19.02, fat: 5.74, carb: 0, fiber: 0, ash: 0.96 },
  },
  {
    id: 'tarantula',
    name: 'Tarantula',
    category: 'insect',
    tags: ['arachnid', 'rainforest'],
    source: 'Modelled from edible-arachnid analyses (chitinous, moderate fat)',
    confidence: 'model',
    coverage: 'macroOnly',
    g: { water: 68, protein: 20, fat: 7, carb: 1, fiber: 2.5, ash: 1.5 },
  },
  {
    id: 'palm_weevil_larva',
    name: 'Palm weevil larva',
    category: 'insect',
    tags: ['insect', 'larva', 'rainforest', 'fatty'],
    source: 'Published Rhynchophorus phoenicis larva analyses converted to fresh weight (fat 15-20 g)',
    confidence: 'low',
    coverage: 'macroOnly',
    g: { water: 67, protein: 9, fat: 20, carb: 1.5, fiber: 1, ash: 1.3 },
  },
  {
    id: 'leafcutter_ant',
    name: 'Leafcutter ant',
    category: 'insect',
    tags: ['insect', 'rainforest', 'high-protein'],
    source: 'Modelled from Atta sexdens (ica) analyses; gravid queens are protein- and fat-dense',
    confidence: 'low',
    coverage: 'macroOnly',
    g: { water: 48, protein: 32, fat: 14, carb: 1.5, fiber: 2.5, ash: 2.5 },
  },
  {
    id: 'cassava_root',
    name: 'Cassava root',
    category: 'vegetable',
    tags: ['root', 'starchy', 'rainforest'],
    source: 'USDA SR Legacy 169985 (Cassava, raw); carb restated net of fibre',
    confidence: 'high',
    coverage: 'full',
    g: { water: 59.68, protein: 1.36, fat: 0.28, carb: 36.26, fiber: 1.8, ash: 0.62 },
    mg: { sodium: 14, potassium: 271, calcium: 16, magnesium: 21, phosphorus: 27, iron: 0.27, zinc: 0.34, copper: 0.1, manganese: 0.384, vitaminB1: 0.087, vitaminB2: 0.048, vitaminB3: 0.854, vitaminB5: 0.107, vitaminB6: 0.088, vitaminC: 20.6 },
    ug: { selenium: 0.7, vitaminB9: 27 },
  },
  {
    id: 'taro',
    name: 'Taro',
    category: 'vegetable',
    tags: ['root', 'starchy', 'wetland'],
    source: 'USDA SR Legacy 169308 (Taro, raw); carb restated net of fibre',
    confidence: 'high',
    coverage: 'full',
    g: { water: 70.64, protein: 1.5, fat: 0.2, carb: 22.36, fiber: 4.1, ash: 1.2 },
    mg: { sodium: 11, potassium: 591, calcium: 43, magnesium: 33, phosphorus: 84, iron: 0.55, zinc: 0.23, copper: 0.172, manganese: 0.383, vitaminB1: 0.095, vitaminB2: 0.025, vitaminB3: 0.6, vitaminB5: 0.303, vitaminB6: 0.283, vitaminC: 4.5 },
    ug: { selenium: 0.7, vitaminB9: 22 },
  },
  {
    id: 'yam',
    name: 'Yam',
    category: 'vegetable',
    tags: ['root', 'starchy', 'rainforest'],
    source: 'USDA SR Legacy 170071 (Yam, raw); carb restated net of fibre; ash set to 1.0 g (literature range 0.8-1.3) so minerals fit',
    confidence: 'medium',
    coverage: 'full',
    g: { water: 69.42, protein: 1.53, fat: 0.17, carb: 23.78, fiber: 4.1, ash: 1 },
    mg: { sodium: 9, potassium: 816, calcium: 17, magnesium: 21, phosphorus: 55, iron: 0.54, zinc: 0.24, copper: 0.178, manganese: 0.397, vitaminB1: 0.112, vitaminB2: 0.032, vitaminB3: 0.552, vitaminB5: 0.314, vitaminB6: 0.293, vitaminC: 17.1 },
    ug: { selenium: 0.7, vitaminB9: 23 },
  },
  {
    id: 'plantain',
    name: 'Plantain',
    category: 'fruit',
    tags: ['fruit', 'starchy', 'rainforest'],
    source: 'USDA SR Legacy 169130 (Plantains, yellow, raw); carb restated net of fibre',
    confidence: 'high',
    coverage: 'full',
    g: { water: 65.2, protein: 1.3, fat: 0.35, carb: 30.19, fiber: 1.7, ash: 1.15 },
    mg: { sodium: 4, potassium: 487, calcium: 3, magnesium: 36, phosphorus: 32, iron: 0.55, zinc: 0.19, copper: 0.074, manganese: 0.144, vitaminB1: 0.062, vitaminB2: 0.076, vitaminB3: 0.672, vitaminB5: 0.3, vitaminB6: 0.242, vitaminC: 18.4 },
    ug: { selenium: 1.5, vitaminA: 56, vitaminK: 28.8, vitaminB9: 22 },
  },
  {
    id: 'breadfruit',
    name: 'Breadfruit',
    category: 'fruit',
    tags: ['fruit', 'starchy', 'rainforest'],
    source: 'USDA SR Legacy 171714 (Breadfruit, raw); carb restated net of fibre',
    confidence: 'high',
    coverage: 'full',
    g: { water: 70.65, protein: 1.07, fat: 0.23, carb: 22.22, fiber: 4.9, ash: 0.93 },
    mg: { sodium: 2, potassium: 490, calcium: 17, magnesium: 25, phosphorus: 30, iron: 0.54, zinc: 0.12, copper: 0.084, manganese: 0.06, vitaminB1: 0.11, vitaminB2: 0.03, vitaminB3: 0.9, vitaminB5: 0.457, vitaminB6: 0.1, vitaminC: 29 },
    ug: { selenium: 0.6, vitaminB9: 14 },
  },
  {
    id: 'jackfruit',
    name: 'Jackfruit',
    category: 'fruit',
    tags: ['fruit', 'rainforest'],
    source: 'USDA SR Legacy 174687 (Jackfruit, raw); carb restated net of fibre',
    confidence: 'high',
    coverage: 'full',
    g: { water: 73.46, protein: 1.72, fat: 0.64, carb: 21.75, fiber: 1.5, ash: 0.94 },
    mg: { sodium: 2, potassium: 448, calcium: 24, magnesium: 29, phosphorus: 21, iron: 0.23, zinc: 0.13, copper: 0.076, manganese: 0.043, vitaminE: 0.34, vitaminB1: 0.105, vitaminB2: 0.055, vitaminB3: 0.92, vitaminB5: 0.235, vitaminB6: 0.329, vitaminC: 13.7 },
    ug: { vitaminA: 5, vitaminB9: 24 },
  },
  {
    id: 'durian',
    name: 'Durian',
    category: 'fruit',
    tags: ['fruit', 'rainforest', 'fatty'],
    source: 'USDA SR Legacy 168192 (Durian, raw or frozen); carb restated net of fibre',
    confidence: 'high',
    coverage: 'full',
    g: { water: 64.99, protein: 1.47, fat: 5.33, carb: 23.29, fiber: 3.8, ash: 1.12 },
    mg: { sodium: 2, potassium: 436, calcium: 6, magnesium: 30, phosphorus: 39, iron: 0.43, zinc: 0.28, copper: 0.207, manganese: 0.325, vitaminB1: 0.374, vitaminB2: 0.2, vitaminB3: 1.074, vitaminB5: 0.23, vitaminB6: 0.316, vitaminC: 19.7 },
    ug: { vitaminA: 2, vitaminB9: 36 },
  },
  {
    id: 'papaya',
    name: 'Papaya',
    category: 'fruit',
    tags: ['fruit', 'rainforest'],
    source: 'USDA SR Legacy 169926 (Papayas, raw); carb restated net of fibre',
    confidence: 'high',
    coverage: 'full',
    g: { water: 88.06, protein: 0.47, fat: 0.26, carb: 9.12, fiber: 1.7, ash: 0.39 },
    mg: { sodium: 8, potassium: 182, calcium: 20, magnesium: 21, phosphorus: 10, iron: 0.25, zinc: 0.08, copper: 0.045, manganese: 0.04, vitaminB1: 0.023, vitaminB2: 0.027, vitaminB3: 0.357, vitaminB5: 0.191, vitaminB6: 0.038, vitaminC: 60.9 },
    ug: { selenium: 0.6, vitaminB9: 37 },
  },
  {
    id: 'guava',
    name: 'Guava',
    category: 'fruit',
    tags: ['fruit', 'rainforest', 'vitamin-c'],
    source: 'USDA SR Legacy 173044 (Guavas, common, raw); carb restated net of fibre',
    confidence: 'high',
    coverage: 'full',
    g: { water: 80.8, protein: 2.55, fat: 0.95, carb: 8.92, fiber: 5.4, ash: 1.39 },
    mg: { sodium: 2, potassium: 417, calcium: 18, magnesium: 22, phosphorus: 40, iron: 0.26, zinc: 0.23, copper: 0.23, manganese: 0.15, vitaminE: 0.73, vitaminB1: 0.067, vitaminB2: 0.04, vitaminB3: 1.084, vitaminB5: 0.451, vitaminB6: 0.11, vitaminC: 228.3 },
    ug: { selenium: 0.6, vitaminA: 31, vitaminK: 2.6, vitaminB9: 49 },
  },
  {
    id: 'passion_fruit',
    name: 'Passion fruit',
    category: 'fruit',
    tags: ['fruit', 'rainforest', 'high-fibre'],
    source: 'USDA SR Legacy 169108 (Passion-fruit, granadilla, purple, raw); carb restated net of fibre',
    confidence: 'high',
    coverage: 'full',
    g: { water: 72.93, protein: 2.2, fat: 0.7, carb: 12.98, fiber: 10.4, ash: 0.8 },
    mg: { sodium: 28, potassium: 348, calcium: 12, magnesium: 29, phosphorus: 68, iron: 1.6, zinc: 0.1, copper: 0.086, vitaminE: 0.02, vitaminB2: 0.13, vitaminB3: 1.5, vitaminB6: 0.1, vitaminC: 30 },
    ug: { selenium: 0.6, vitaminA: 64, vitaminK: 0.7, vitaminB9: 14 },
  },
  {
    id: 'acai',
    name: 'Acai',
    category: 'fruit',
    tags: ['fruit', 'rainforest', 'fatty'],
    source: 'Published Euterpe oleracea frozen-pulp composition (Food Sci. Technol. Campinas; genotype survey)',
    confidence: 'low',
    coverage: 'macroOnly',
    g: { water: 89, protein: 0.8, fat: 3.8, carb: 2.5, fiber: 3, ash: 0.5 },
  },
  {
    id: 'palm_heart',
    name: 'Palm heart',
    category: 'vegetable',
    tags: ['vegetable', 'rainforest'],
    source: 'USDA SR Legacy 167714 (Hearts of palm, raw); carb restated net of fibre; phosphorus omitted so minerals fit below ash',
    confidence: 'high',
    coverage: 'full',
    g: { water: 69.5, protein: 2.7, fat: 0.2, carb: 24.11, fiber: 1.5, ash: 1.99 },
    mg: { sodium: 14, potassium: 1806, calcium: 18, magnesium: 10, iron: 1.69, zinc: 3.73, copper: 0.644, vitaminB1: 0.05, vitaminB2: 0.18, vitaminB3: 0.9, vitaminB6: 0.81, vitaminC: 8 },
    ug: { selenium: 0.7, vitaminB9: 24 },
  },
  {
    id: 'palm_oil',
    name: 'Palm oil',
    category: 'fat',
    tags: ['plant-fat', 'rainforest', 'vitamin-e'],
    source: 'USDA SR Legacy 171015 (Oil, palm); trace ash assigned',
    confidence: 'high',
    coverage: 'partial',
    g: { water: 0.02, protein: 0, fat: 99.96, carb: 0, fiber: 0, ash: 0.02 },
    mg: { vitaminE: 15.94 },
    ug: { vitaminK: 8 },
  },
  {
    id: 'cocoa_bean',
    name: 'Cocoa bean',
    category: 'refined',
    tags: ['seed', 'rainforest', 'high-mineral'],
    source: 'USDA SR Legacy 169593 (Cocoa, dry powder, unsweetened); carb restated net of fibre',
    confidence: 'high',
    coverage: 'full',
    g: { water: 3, protein: 19.6, fat: 13.7, carb: 20.9, fiber: 37, ash: 5.8 },
    mg: { sodium: 21, potassium: 1524, calcium: 128, magnesium: 499, phosphorus: 734, iron: 13.86, zinc: 6.81, copper: 3.788, manganese: 3.837, vitaminE: 0.1, vitaminB1: 0.078, vitaminB2: 0.241, vitaminB3: 2.185, vitaminB5: 0.254, vitaminB6: 0.118 },
    ug: { selenium: 14.3, vitaminK: 2.5, vitaminB9: 32 },
  },
  {
    id: 'bamboo_shoot',
    name: 'Bamboo shoot',
    category: 'vegetable',
    tags: ['shoot', 'rainforest'],
    source: 'USDA SR Legacy 169210 (Bamboo shoots, raw); carb restated net of fibre',
    confidence: 'high',
    coverage: 'full',
    g: { water: 91, protein: 2.6, fat: 0.3, carb: 3, fiber: 2.2, ash: 0.9 },
    mg: { sodium: 4, potassium: 533, calcium: 13, magnesium: 3, phosphorus: 59, iron: 0.5, zinc: 1.1, copper: 0.19, manganese: 0.262, vitaminB1: 0.15, vitaminB2: 0.07, vitaminB3: 0.6, vitaminB5: 0.161, vitaminB6: 0.24, vitaminC: 4 },
    ug: { selenium: 0.8, vitaminB9: 7 },
  },
  {
    id: 'wild_rice',
    name: 'Wild rice',
    category: 'grain',
    tags: ['grain', 'wetland'],
    source: 'USDA SR Legacy 169726 (Wild rice, raw); carb restated net of fibre',
    confidence: 'high',
    coverage: 'full',
    g: { water: 7.76, protein: 14.73, fat: 1.08, carb: 68.7, fiber: 6.2, ash: 1.53 },
    mg: { sodium: 7, potassium: 427, calcium: 21, magnesium: 177, phosphorus: 433, iron: 1.96, zinc: 5.96, copper: 0.524, manganese: 1.329, vitaminE: 0.82, vitaminB1: 0.115, vitaminB2: 0.262, vitaminB3: 6.733, vitaminB5: 1.074, vitaminB6: 0.391 },
    ug: { selenium: 2.8, vitaminA: 1, vitaminK: 1.9, vitaminB9: 95 },
  },
  {
    id: 'watercress',
    name: 'Watercress',
    category: 'vegetable',
    tags: ['wild-green', 'wetland'],
    source: 'USDA SR Legacy 170068 (Watercress, raw); carb restated net of fibre',
    confidence: 'high',
    coverage: 'full',
    g: { water: 95.11, protein: 2.3, fat: 0.1, carb: 0.79, fiber: 0.5, ash: 1.2 },
    mg: { sodium: 41, potassium: 330, calcium: 120, magnesium: 21, phosphorus: 60, iron: 0.2, zinc: 0.11, copper: 0.077, manganese: 0.244, vitaminB1: 0.09, vitaminB2: 0.12, vitaminB3: 0.2, vitaminB5: 0.31, vitaminB6: 0.129, vitaminC: 43 },
    ug: { selenium: 0.9, vitaminB9: 9 },
  },
  {
    id: 'water_chestnut',
    name: 'Water chestnut',
    category: 'vegetable',
    tags: ['corm', 'wetland', 'starchy'],
    source: 'USDA SR Legacy 170066 (Waterchestnuts, chinese, matai, raw); carb restated net of fibre',
    confidence: 'high',
    coverage: 'full',
    g: { water: 73.46, protein: 1.4, fat: 0.1, carb: 20.94, fiber: 3, ash: 1.1 },
    mg: { sodium: 14, potassium: 584, calcium: 11, magnesium: 22, phosphorus: 63, iron: 0.06, zinc: 0.5, copper: 0.326, manganese: 0.331, vitaminB1: 0.14, vitaminB2: 0.2, vitaminB3: 1, vitaminB5: 0.479, vitaminB6: 0.328, vitaminC: 4 },
    ug: { selenium: 0.7, vitaminB9: 16 },
  },
  {
    id: 'lotus_root',
    name: 'Lotus root',
    category: 'vegetable',
    tags: ['rhizome', 'wetland', 'starchy'],
    source: 'USDA SR Legacy 169250 (Lotus root, raw); carb restated net of fibre',
    confidence: 'high',
    coverage: 'full',
    g: { water: 79.1, protein: 2.6, fat: 0.1, carb: 12.33, fiber: 4.9, ash: 0.97 },
    mg: { sodium: 40, potassium: 556, calcium: 45, magnesium: 23, phosphorus: 100, iron: 1.16, zinc: 0.39, copper: 0.257, manganese: 0.261, vitaminB1: 0.16, vitaminB2: 0.22, vitaminB3: 0.4, vitaminB5: 0.377, vitaminB6: 0.258, vitaminC: 44 },
    ug: { selenium: 0.7, vitaminB9: 13 },
  },
  {
    id: 'frog_legs',
    name: 'Frog legs',
    category: 'meat',
    tags: ['amphibian', 'wetland', 'lean'],
    source: 'USDA SR Legacy 168148 (Frog legs, raw)',
    confidence: 'high',
    coverage: 'full',
    g: { water: 81.9, protein: 16.4, fat: 0.3, carb: 0, fiber: 0, ash: 1.4 },
    mg: { sodium: 58, potassium: 285, calcium: 18, magnesium: 20, phosphorus: 147, iron: 1.5, zinc: 1, copper: 0.25, vitaminB1: 0.14, vitaminB2: 0.25, vitaminB3: 1.2, vitaminB6: 0.12 },
    ug: { selenium: 14.1, vitaminB9: 15, vitaminB12: 0.4 },
  },
  {
    id: 'escargot',
    name: 'Escargot (land snail)',
    category: 'meat',
    tags: ['mollusc', 'gastropod', 'wetland'],
    source: 'USDA SR Legacy 167744 (Mollusks, snail, raw)',
    confidence: 'high',
    coverage: 'full',
    g: { water: 79.2, protein: 16.1, fat: 1.4, carb: 2, fiber: 0, ash: 1.3 },
    mg: { sodium: 70, potassium: 382, calcium: 10, magnesium: 250, phosphorus: 272, iron: 3.5, zinc: 1, copper: 0.4, vitaminE: 5, vitaminB1: 0.01, vitaminB2: 0.12, vitaminB3: 1.4, vitaminB6: 0.13 },
    ug: { selenium: 27.4, vitaminA: 30, vitaminK: 0.1, vitaminB9: 6, vitaminB12: 0.5 },
  },
  {
    id: 'papyrus_rhizome',
    name: 'Papyrus rhizome',
    category: 'vegetable',
    tags: ['rhizome', 'wetland', 'starchy'],
    source: 'Modelled from Cyperus papyrus rhizome analyses (starchy, fibrous)',
    confidence: 'model',
    coverage: 'macroOnly',
    g: { water: 74, protein: 2, fat: 0.4, carb: 16, fiber: 6, ash: 1.4 },
  },
  {
    id: 'peat',
    name: 'Peat',
    category: 'material',
    tags: ['organic-matter', 'wetland', 'indigestible'],
    source: 'Modelled from Sphagnum peat proximate analyses (lignocellulose and humic residue; not a food)',
    confidence: 'model',
    coverage: 'macroOnly',
    g: { water: 15, protein: 2, fat: 1, carb: 20, fiber: 58, ash: 3.5 },
  },
];
